// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ErrorsInitParameters struct {
}

type ErrorsObservation struct {
	Code *float64 `json:"code,omitempty" tf:"code,omitempty"`

	DocumentationURL *string `json:"documentationUrl,omitempty" tf:"documentation_url,omitempty"`

	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	Source *SourceObservation `json:"source,omitempty" tf:"source,omitempty"`
}

type ErrorsParameters struct {
}

type MessagesInitParameters struct {
}

type MessagesObservation struct {
	Code *float64 `json:"code,omitempty" tf:"code,omitempty"`

	DocumentationURL *string `json:"documentationUrl,omitempty" tf:"documentation_url,omitempty"`

	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	Source *MessagesSourceObservation `json:"source,omitempty" tf:"source,omitempty"`
}

type MessagesParameters struct {
}

type MessagesSourceInitParameters struct {
}

type MessagesSourceObservation struct {
	Pointer *string `json:"pointer,omitempty" tf:"pointer,omitempty"`
}

type MessagesSourceParameters struct {
}

type MissingInitParameters struct {
}

type MissingObservation struct {

	// DNS record content.
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// DNS record name (or @ for the zone apex).
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Required for MX, SRV and URI records. Unused by other record types. Records with lower priorities are preferred.
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// Time to live, in seconds, of the DNS record. Must be between 60 and 86400, or 1 for 'automatic'.
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`

	// DNS record type.
	// Available values: "A", "AAAA", "CNAME", "HTTPS", "TXT", "SRV", "LOC", "MX", "NS", "CERT", "DNSKEY", "DS", "NAPTR", "SMIMEA", "SSHFP", "SVCB", "TLSA", "URI".
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type MissingParameters struct {
}

type RecordInitParameters struct {
}

type RecordObservation struct {

	// DNS record content.
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	// DNS record name (or @ for the zone apex).
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Required for MX, SRV and URI records. Unused by other record types. Records with lower priorities are preferred.
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// Time to live, in seconds, of the DNS record. Must be between 60 and 86400, or 1 for 'automatic'.
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`

	// DNS record type.
	// Available values: "A", "AAAA", "CNAME", "HTTPS", "TXT", "SRV", "LOC", "MX", "NS", "CERT", "DNSKEY", "DS", "NAPTR", "SMIMEA", "SSHFP", "SVCB", "TLSA", "URI".
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type RecordParameters struct {
}

type ResultErrorsInitParameters struct {
}

type ResultErrorsObservation struct {
	Code *string `json:"code,omitempty" tf:"code,omitempty"`

	Missing *MissingObservation `json:"missing,omitempty" tf:"missing,omitempty"`
}

type ResultErrorsParameters struct {
}

type ResultInfoInitParameters struct {
}

type ResultInfoObservation struct {

	// Total number of results for the requested service.
	EmailRoutingDNSCount *float64 `json:"emailRoutingDnsCount,omitempty" tf:"email_routing_dns_count,omitempty"`

	// Current page within paginated list of results.
	Page *float64 `json:"page,omitempty" tf:"page,omitempty"`

	// Number of results per page of results.
	PerPage *float64 `json:"perPage,omitempty" tf:"per_page,omitempty"`

	// Total results available without any search parameters.
	TotalCount *float64 `json:"totalCount,omitempty" tf:"total_count,omitempty"`
}

type ResultInfoParameters struct {
}

type ResultInitParameters struct {
}

type ResultObservation struct {

	// DNS record content.
	Content *string `json:"content,omitempty" tf:"content,omitempty"`

	Errors []ResultErrorsObservation `json:"errors,omitempty" tf:"errors,omitempty"`

	// DNS record name (or @ for the zone apex).
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Required for MX, SRV and URI records. Unused by other record types. Records with lower priorities are preferred.
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`

	Record []RecordObservation `json:"record,omitempty" tf:"record,omitempty"`

	// Time to live, in seconds, of the DNS record. Must be between 60 and 86400, or 1 for 'automatic'.
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`

	// DNS record type.
	// Available values: "A", "AAAA", "CNAME", "HTTPS", "TXT", "SRV", "LOC", "MX", "NS", "CERT", "DNSKEY", "DS", "NAPTR", "SMIMEA", "SSHFP", "SVCB", "TLSA", "URI".
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ResultParameters struct {
}

type RoutingDNSInitParameters struct {

	// Domain of your zone.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Identifier.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type RoutingDNSObservation struct {

	// The date and time the settings have been created.
	Created *string `json:"created,omitempty" tf:"created,omitempty"`

	// State of the zone settings for Email Routing.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	Errors []ErrorsObservation `json:"errors,omitempty" tf:"errors,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Messages []MessagesObservation `json:"messages,omitempty" tf:"messages,omitempty"`

	// The date and time the settings have been modified.
	Modified *string `json:"modified,omitempty" tf:"modified,omitempty"`

	// Domain of your zone.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Result *ResultObservation `json:"result,omitempty" tf:"result,omitempty"`

	ResultInfo *ResultInfoObservation `json:"resultInfo,omitempty" tf:"result_info,omitempty"`

	// Flag to check if the user skipped the configuration wizard.
	SkipWizard *bool `json:"skipWizard,omitempty" tf:"skip_wizard,omitempty"`

	// Show the state of your account, and the type or configuration error.
	// Available values: "ready", "unconfigured", "misconfigured", "misconfigured/locked", "unlocked".
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Whether the API call was successful.
	Success *bool `json:"success,omitempty" tf:"success,omitempty"`

	// Email Routing settings tag. (Deprecated, replaced by Email Routing settings identifier)
	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`

	// Identifier.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type RoutingDNSParameters struct {

	// Domain of your zone.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Identifier.
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type SourceInitParameters struct {
}

type SourceObservation struct {
	Pointer *string `json:"pointer,omitempty" tf:"pointer,omitempty"`
}

type SourceParameters struct {
}

// RoutingDNSSpec defines the desired state of RoutingDNS
type RoutingDNSSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RoutingDNSParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RoutingDNSInitParameters `json:"initProvider,omitempty"`
}

// RoutingDNSStatus defines the observed state of RoutingDNS.
type RoutingDNSStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RoutingDNSObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RoutingDNS is the Schema for the RoutingDNSs API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type RoutingDNS struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zoneId) || (has(self.initProvider) && has(self.initProvider.zoneId))",message="spec.forProvider.zoneId is a required parameter"
	Spec   RoutingDNSSpec   `json:"spec"`
	Status RoutingDNSStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RoutingDNSList contains a list of RoutingDNSs
type RoutingDNSList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RoutingDNS `json:"items"`
}

// Repository type metadata.
var (
	RoutingDNS_Kind             = "RoutingDNS"
	RoutingDNS_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RoutingDNS_Kind}.String()
	RoutingDNS_KindAPIVersion   = RoutingDNS_Kind + "." + CRDGroupVersion.String()
	RoutingDNS_GroupVersionKind = CRDGroupVersion.WithKind(RoutingDNS_Kind)
)

func init() {
	SchemeBuilder.Register(&RoutingDNS{}, &RoutingDNSList{})
}
