// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AccountInitParameters struct {
	ManagedBy *ManagedByInitParameters `json:"managedBy,omitempty" tf:"managed_by,omitempty"`

	// Account name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Settings *SettingsInitParameters `json:"settings,omitempty" tf:"settings,omitempty"`

	// Available values: "standard", "enterprise".
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	Unit *UnitInitParameters `json:"unit,omitempty" tf:"unit,omitempty"`
}

type AccountObservation struct {

	// Timestamp for the creation of the account
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	ManagedBy *ManagedByObservation `json:"managedBy,omitempty" tf:"managed_by,omitempty"`

	// Account name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Settings *SettingsObservation `json:"settings,omitempty" tf:"settings,omitempty"`

	// Available values: "standard", "enterprise".
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	Unit *UnitObservation `json:"unit,omitempty" tf:"unit,omitempty"`
}

type AccountParameters struct {

	// +kubebuilder:validation:Optional
	ManagedBy *ManagedByParameters `json:"managedBy,omitempty" tf:"managed_by,omitempty"`

	// Account name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	Settings *SettingsParameters `json:"settings,omitempty" tf:"settings,omitempty"`

	// Available values: "standard", "enterprise".
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// +kubebuilder:validation:Optional
	Unit *UnitParameters `json:"unit,omitempty" tf:"unit,omitempty"`
}

type ManagedByInitParameters struct {
}

type ManagedByObservation struct {

	// ID of the parent Organization, if one exists
	ParentOrgID *string `json:"parentOrgId,omitempty" tf:"parent_org_id,omitempty"`

	// Name of the parent Organization, if one exists
	ParentOrgName *string `json:"parentOrgName,omitempty" tf:"parent_org_name,omitempty"`
}

type ManagedByParameters struct {
}

type SettingsInitParameters struct {

	// Sets an abuse contact email to notify for abuse reports.
	AbuseContactEmail *string `json:"abuseContactEmail,omitempty" tf:"abuse_contact_email,omitempty"`

	// Indicates whether membership in this account requires that
	// Two-Factor Authentication is enabled
	EnforceTwofactor *bool `json:"enforceTwofactor,omitempty" tf:"enforce_twofactor,omitempty"`
}

type SettingsObservation struct {

	// Sets an abuse contact email to notify for abuse reports.
	AbuseContactEmail *string `json:"abuseContactEmail,omitempty" tf:"abuse_contact_email,omitempty"`

	// Indicates whether membership in this account requires that
	// Two-Factor Authentication is enabled
	EnforceTwofactor *bool `json:"enforceTwofactor,omitempty" tf:"enforce_twofactor,omitempty"`
}

type SettingsParameters struct {

	// Sets an abuse contact email to notify for abuse reports.
	// +kubebuilder:validation:Optional
	AbuseContactEmail *string `json:"abuseContactEmail,omitempty" tf:"abuse_contact_email,omitempty"`

	// Indicates whether membership in this account requires that
	// Two-Factor Authentication is enabled
	// +kubebuilder:validation:Optional
	EnforceTwofactor *bool `json:"enforceTwofactor,omitempty" tf:"enforce_twofactor,omitempty"`
}

type UnitInitParameters struct {

	// Tenant unit ID
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type UnitObservation struct {

	// Tenant unit ID
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type UnitParameters struct {

	// Tenant unit ID
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

// AccountSpec defines the desired state of Account
type AccountSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AccountParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AccountInitParameters `json:"initProvider,omitempty"`
}

// AccountStatus defines the observed state of Account.
type AccountStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AccountObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Account is the Schema for the Accounts API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type Account struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   AccountSpec   `json:"spec"`
	Status AccountStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountList contains a list of Accounts
type AccountList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Account `json:"items"`
}

// Repository type metadata.
var (
	Account_Kind             = "Account"
	Account_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Account_Kind}.String()
	Account_KindAPIVersion   = Account_Kind + "." + CRDGroupVersion.String()
	Account_GroupVersionKind = CRDGroupVersion.WithKind(Account_Kind)
)

func init() {
	SchemeBuilder.Register(&Account{}, &AccountList{})
}
