// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type FlagsInitParameters struct {
}

type FlagsObservation struct {
	AccountCreation *string `json:"accountCreation,omitempty" tf:"account_creation,omitempty"`

	AccountDeletion *string `json:"accountDeletion,omitempty" tf:"account_deletion,omitempty"`

	AccountMigration *string `json:"accountMigration,omitempty" tf:"account_migration,omitempty"`

	AccountMobility *string `json:"accountMobility,omitempty" tf:"account_mobility,omitempty"`

	SubOrgCreation *string `json:"subOrgCreation,omitempty" tf:"sub_org_creation,omitempty"`
}

type FlagsParameters struct {
}

type MetaInitParameters struct {
}

type MetaObservation struct {
	Flags *FlagsObservation `json:"flags,omitempty" tf:"flags,omitempty"`

	ManagedBy *string `json:"managedBy,omitempty" tf:"managed_by,omitempty"`
}

type MetaParameters struct {
}

type OrganizationInitParameters struct {
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Parent *ParentInitParameters `json:"parent,omitempty" tf:"parent,omitempty"`

	Profile *ProfileInitParameters `json:"profile,omitempty" tf:"profile,omitempty"`
}

type OrganizationObservation struct {
	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Meta *MetaObservation `json:"meta,omitempty" tf:"meta,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Parent *ParentObservation `json:"parent,omitempty" tf:"parent,omitempty"`

	Profile *ProfileObservation `json:"profile,omitempty" tf:"profile,omitempty"`
}

type OrganizationParameters struct {

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	Parent *ParentParameters `json:"parent,omitempty" tf:"parent,omitempty"`

	// +kubebuilder:validation:Optional
	Profile *ProfileParameters `json:"profile,omitempty" tf:"profile,omitempty"`
}

type ParentInitParameters struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type ParentObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type ParentParameters struct {

	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type ProfileInitParameters struct {
	BusinessAddress *string `json:"businessAddress,omitempty" tf:"business_address,omitempty"`

	BusinessEmail *string `json:"businessEmail,omitempty" tf:"business_email,omitempty"`

	BusinessName *string `json:"businessName,omitempty" tf:"business_name,omitempty"`

	BusinessPhone *string `json:"businessPhone,omitempty" tf:"business_phone,omitempty"`

	ExternalMetadata *string `json:"externalMetadata,omitempty" tf:"external_metadata,omitempty"`
}

type ProfileObservation struct {
	BusinessAddress *string `json:"businessAddress,omitempty" tf:"business_address,omitempty"`

	BusinessEmail *string `json:"businessEmail,omitempty" tf:"business_email,omitempty"`

	BusinessName *string `json:"businessName,omitempty" tf:"business_name,omitempty"`

	BusinessPhone *string `json:"businessPhone,omitempty" tf:"business_phone,omitempty"`

	ExternalMetadata *string `json:"externalMetadata,omitempty" tf:"external_metadata,omitempty"`
}

type ProfileParameters struct {

	// +kubebuilder:validation:Optional
	BusinessAddress *string `json:"businessAddress" tf:"business_address,omitempty"`

	// +kubebuilder:validation:Optional
	BusinessEmail *string `json:"businessEmail" tf:"business_email,omitempty"`

	// +kubebuilder:validation:Optional
	BusinessName *string `json:"businessName" tf:"business_name,omitempty"`

	// +kubebuilder:validation:Optional
	BusinessPhone *string `json:"businessPhone" tf:"business_phone,omitempty"`

	// +kubebuilder:validation:Optional
	ExternalMetadata *string `json:"externalMetadata" tf:"external_metadata,omitempty"`
}

// OrganizationSpec defines the desired state of Organization
type OrganizationSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     OrganizationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OrganizationInitParameters `json:"initProvider,omitempty"`
}

// OrganizationStatus defines the observed state of Organization.
type OrganizationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        OrganizationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Organization is the Schema for the Organizations API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type Organization struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   OrganizationSpec   `json:"spec"`
	Status OrganizationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OrganizationList contains a list of Organizations
type OrganizationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Organization `json:"items"`
}

// Repository type metadata.
var (
	Organization_Kind             = "Organization"
	Organization_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Organization_Kind}.String()
	Organization_KindAPIVersion   = Organization_Kind + "." + CRDGroupVersion.String()
	Organization_GroupVersionKind = CRDGroupVersion.WithKind(Organization_Kind)
)

func init() {
	SchemeBuilder.Register(&Organization{}, &OrganizationList{})
}
