// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type InstancesInitParameters struct {
}

type InstancesObservation struct {
	Complete *float64 `json:"complete,omitempty" tf:"complete,omitempty"`

	Errored *float64 `json:"errored,omitempty" tf:"errored,omitempty"`

	Paused *float64 `json:"paused,omitempty" tf:"paused,omitempty"`

	Queued *float64 `json:"queued,omitempty" tf:"queued,omitempty"`

	Running *float64 `json:"running,omitempty" tf:"running,omitempty"`

	Terminated *float64 `json:"terminated,omitempty" tf:"terminated,omitempty"`

	Waiting *float64 `json:"waiting,omitempty" tf:"waiting,omitempty"`

	WaitingForPause *float64 `json:"waitingForPause,omitempty" tf:"waiting_for_pause,omitempty"`
}

type InstancesParameters struct {
}

type WorkflowInitParameters struct {
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	ClassName *string `json:"className,omitempty" tf:"class_name,omitempty"`

	ScriptName *string `json:"scriptName,omitempty" tf:"script_name,omitempty"`

	WorkflowName *string `json:"workflowName,omitempty" tf:"workflow_name,omitempty"`
}

type WorkflowObservation struct {
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	ClassName *string `json:"className,omitempty" tf:"class_name,omitempty"`

	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Instances *InstancesObservation `json:"instances,omitempty" tf:"instances,omitempty"`

	IsDeleted *float64 `json:"isDeleted,omitempty" tf:"is_deleted,omitempty"`

	ModifiedOn *string `json:"modifiedOn,omitempty" tf:"modified_on,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	ScriptName *string `json:"scriptName,omitempty" tf:"script_name,omitempty"`

	TerminatorRunning *float64 `json:"terminatorRunning,omitempty" tf:"terminator_running,omitempty"`

	TriggeredOn *string `json:"triggeredOn,omitempty" tf:"triggered_on,omitempty"`

	VersionID *string `json:"versionId,omitempty" tf:"version_id,omitempty"`

	WorkflowName *string `json:"workflowName,omitempty" tf:"workflow_name,omitempty"`
}

type WorkflowParameters struct {

	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// +kubebuilder:validation:Optional
	ClassName *string `json:"className,omitempty" tf:"class_name,omitempty"`

	// +kubebuilder:validation:Optional
	ScriptName *string `json:"scriptName,omitempty" tf:"script_name,omitempty"`

	// +kubebuilder:validation:Optional
	WorkflowName *string `json:"workflowName,omitempty" tf:"workflow_name,omitempty"`
}

// WorkflowSpec defines the desired state of Workflow
type WorkflowSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     WorkflowParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider WorkflowInitParameters `json:"initProvider,omitempty"`
}

// WorkflowStatus defines the observed state of Workflow.
type WorkflowStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        WorkflowObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Workflow is the Schema for the Workflows API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type Workflow struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.accountId) || (has(self.initProvider) && has(self.initProvider.accountId))",message="spec.forProvider.accountId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.className) || (has(self.initProvider) && has(self.initProvider.className))",message="spec.forProvider.className is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.scriptName) || (has(self.initProvider) && has(self.initProvider.scriptName))",message="spec.forProvider.scriptName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.workflowName) || (has(self.initProvider) && has(self.initProvider.workflowName))",message="spec.forProvider.workflowName is a required parameter"
	Spec   WorkflowSpec   `json:"spec"`
	Status WorkflowStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WorkflowList contains a list of Workflows
type WorkflowList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Workflow `json:"items"`
}

// Repository type metadata.
var (
	Workflow_Kind             = "Workflow"
	Workflow_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Workflow_Kind}.String()
	Workflow_KindAPIVersion   = Workflow_Kind + "." + CRDGroupVersion.String()
	Workflow_GroupVersionKind = CRDGroupVersion.WithKind(Workflow_Kind)
)

func init() {
	SchemeBuilder.Register(&Workflow{}, &WorkflowList{})
}
