// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type HostnameInitParameters struct {

	// Only applies to wildcard hostnames (e.g., *.example.com). When true (default), only subdomains are blocked. When false, both the root domain and subdomains are blocked.
	ExcludeExactHostname *bool `json:"excludeExactHostname,omitempty" tf:"exclude_exact_hostname,omitempty"`

	URLHostname *string `json:"urlHostname,omitempty" tf:"url_hostname,omitempty"`
}

type HostnameObservation struct {

	// Only applies to wildcard hostnames (e.g., *.example.com). When true (default), only subdomains are blocked. When false, both the root domain and subdomains are blocked.
	ExcludeExactHostname *bool `json:"excludeExactHostname,omitempty" tf:"exclude_exact_hostname,omitempty"`

	URLHostname *string `json:"urlHostname,omitempty" tf:"url_hostname,omitempty"`
}

type HostnameParameters struct {

	// Only applies to wildcard hostnames (e.g., *.example.com). When true (default), only subdomains are blocked. When false, both the root domain and subdomains are blocked.
	// +kubebuilder:validation:Optional
	ExcludeExactHostname *bool `json:"excludeExactHostname,omitempty" tf:"exclude_exact_hostname,omitempty"`

	// +kubebuilder:validation:Optional
	URLHostname *string `json:"urlHostname" tf:"url_hostname,omitempty"`
}

type ItemInitParameters struct {

	// The Account ID for this resource.
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// A non-negative 32 bit integer
	Asn *float64 `json:"asn,omitempty" tf:"asn,omitempty"`

	// An informative summary of the list item.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	Hostname *HostnameInitParameters `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// An IPv4 address, an IPv4 CIDR, an IPv6 address, or an IPv6 CIDR.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// The unique ID of the list.
	ListID *string `json:"listId,omitempty" tf:"list_id,omitempty"`

	Redirect *RedirectInitParameters `json:"redirect,omitempty" tf:"redirect,omitempty"`
}

type ItemObservation struct {

	// The Account ID for this resource.
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// A non-negative 32 bit integer
	Asn *float64 `json:"asn,omitempty" tf:"asn,omitempty"`

	// An informative summary of the list item.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// The RFC 3339 timestamp of when the item was created.
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	Hostname *HostnameObservation `json:"hostname,omitempty" tf:"hostname,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// An IPv4 address, an IPv4 CIDR, an IPv6 address, or an IPv6 CIDR.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// The unique ID of the list.
	ListID *string `json:"listId,omitempty" tf:"list_id,omitempty"`

	// The RFC 3339 timestamp of when the item was last modified.
	ModifiedOn *string `json:"modifiedOn,omitempty" tf:"modified_on,omitempty"`

	// The unique operation ID of the asynchronous action.
	OperationID *string `json:"operationId,omitempty" tf:"operation_id,omitempty"`

	Redirect *RedirectObservation `json:"redirect,omitempty" tf:"redirect,omitempty"`
}

type ItemParameters struct {

	// The Account ID for this resource.
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// A non-negative 32 bit integer
	// +kubebuilder:validation:Optional
	Asn *float64 `json:"asn,omitempty" tf:"asn,omitempty"`

	// An informative summary of the list item.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// +kubebuilder:validation:Optional
	Hostname *HostnameParameters `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// An IPv4 address, an IPv4 CIDR, an IPv6 address, or an IPv6 CIDR.
	// +kubebuilder:validation:Optional
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// The unique ID of the list.
	// +kubebuilder:validation:Optional
	ListID *string `json:"listId,omitempty" tf:"list_id,omitempty"`

	// +kubebuilder:validation:Optional
	Redirect *RedirectParameters `json:"redirect,omitempty" tf:"redirect,omitempty"`
}

type RedirectInitParameters struct {
	IncludeSubdomains *bool `json:"includeSubdomains,omitempty" tf:"include_subdomains,omitempty"`

	PreservePathSuffix *bool `json:"preservePathSuffix,omitempty" tf:"preserve_path_suffix,omitempty"`

	PreserveQueryString *bool `json:"preserveQueryString,omitempty" tf:"preserve_query_string,omitempty"`

	SourceURL *string `json:"sourceUrl,omitempty" tf:"source_url,omitempty"`

	// Available values: 301, 302, 307, 308.
	StatusCode *float64 `json:"statusCode,omitempty" tf:"status_code,omitempty"`

	SubpathMatching *bool `json:"subpathMatching,omitempty" tf:"subpath_matching,omitempty"`

	TargetURL *string `json:"targetUrl,omitempty" tf:"target_url,omitempty"`
}

type RedirectObservation struct {
	IncludeSubdomains *bool `json:"includeSubdomains,omitempty" tf:"include_subdomains,omitempty"`

	PreservePathSuffix *bool `json:"preservePathSuffix,omitempty" tf:"preserve_path_suffix,omitempty"`

	PreserveQueryString *bool `json:"preserveQueryString,omitempty" tf:"preserve_query_string,omitempty"`

	SourceURL *string `json:"sourceUrl,omitempty" tf:"source_url,omitempty"`

	// Available values: 301, 302, 307, 308.
	StatusCode *float64 `json:"statusCode,omitempty" tf:"status_code,omitempty"`

	SubpathMatching *bool `json:"subpathMatching,omitempty" tf:"subpath_matching,omitempty"`

	TargetURL *string `json:"targetUrl,omitempty" tf:"target_url,omitempty"`
}

type RedirectParameters struct {

	// +kubebuilder:validation:Optional
	IncludeSubdomains *bool `json:"includeSubdomains,omitempty" tf:"include_subdomains,omitempty"`

	// +kubebuilder:validation:Optional
	PreservePathSuffix *bool `json:"preservePathSuffix,omitempty" tf:"preserve_path_suffix,omitempty"`

	// +kubebuilder:validation:Optional
	PreserveQueryString *bool `json:"preserveQueryString,omitempty" tf:"preserve_query_string,omitempty"`

	// +kubebuilder:validation:Optional
	SourceURL *string `json:"sourceUrl" tf:"source_url,omitempty"`

	// Available values: 301, 302, 307, 308.
	// +kubebuilder:validation:Optional
	StatusCode *float64 `json:"statusCode,omitempty" tf:"status_code,omitempty"`

	// +kubebuilder:validation:Optional
	SubpathMatching *bool `json:"subpathMatching,omitempty" tf:"subpath_matching,omitempty"`

	// +kubebuilder:validation:Optional
	TargetURL *string `json:"targetUrl" tf:"target_url,omitempty"`
}

// ItemSpec defines the desired state of Item
type ItemSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ItemParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ItemInitParameters `json:"initProvider,omitempty"`
}

// ItemStatus defines the observed state of Item.
type ItemStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ItemObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Item is the Schema for the Items API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type Item struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.accountId) || (has(self.initProvider) && has(self.initProvider.accountId))",message="spec.forProvider.accountId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.listId) || (has(self.initProvider) && has(self.initProvider.listId))",message="spec.forProvider.listId is a required parameter"
	Spec   ItemSpec   `json:"spec"`
	Status ItemStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ItemList contains a list of Items
type ItemList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Item `json:"items"`
}

// Repository type metadata.
var (
	Item_Kind             = "Item"
	Item_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Item_Kind}.String()
	Item_KindAPIVersion   = Item_Kind + "." + CRDGroupVersion.String()
	Item_GroupVersionKind = CRDGroupVersion.WithKind(Item_Kind)
)

func init() {
	SchemeBuilder.Register(&Item{}, &ItemList{})
}
