// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ActionsInitParameters struct {
	AlwaysUseHTTPS *bool `json:"alwaysUseHttps,omitempty" tf:"always_use_https,omitempty"`

	AutomaticHTTPSRewrites *string `json:"automaticHttpsRewrites,omitempty" tf:"automatic_https_rewrites,omitempty"`

	BrowserCacheTTL *float64 `json:"browserCacheTtl,omitempty" tf:"browser_cache_ttl,omitempty"`

	BrowserCheck *string `json:"browserCheck,omitempty" tf:"browser_check,omitempty"`

	BypassCacheOnCookie *string `json:"bypassCacheOnCookie,omitempty" tf:"bypass_cache_on_cookie,omitempty"`

	CacheByDeviceType *string `json:"cacheByDeviceType,omitempty" tf:"cache_by_device_type,omitempty"`

	CacheDeceptionArmor *string `json:"cacheDeceptionArmor,omitempty" tf:"cache_deception_armor,omitempty"`

	CacheKeyFields *CacheKeyFieldsInitParameters `json:"cacheKeyFields,omitempty" tf:"cache_key_fields,omitempty"`

	CacheLevel *string `json:"cacheLevel,omitempty" tf:"cache_level,omitempty"`

	CacheOnCookie *string `json:"cacheOnCookie,omitempty" tf:"cache_on_cookie,omitempty"`

	// +mapType=granular
	CacheTTLByStatus map[string]*string `json:"cacheTtlByStatus,omitempty" tf:"cache_ttl_by_status,omitempty"`

	DisableApps *bool `json:"disableApps,omitempty" tf:"disable_apps,omitempty"`

	DisablePerformance *bool `json:"disablePerformance,omitempty" tf:"disable_performance,omitempty"`

	DisableSecurity *bool `json:"disableSecurity,omitempty" tf:"disable_security,omitempty"`

	DisableZaraz *bool `json:"disableZaraz,omitempty" tf:"disable_zaraz,omitempty"`

	EdgeCacheTTL *float64 `json:"edgeCacheTtl,omitempty" tf:"edge_cache_ttl,omitempty"`

	EmailObfuscation *string `json:"emailObfuscation,omitempty" tf:"email_obfuscation,omitempty"`

	ExplicitCacheControl *string `json:"explicitCacheControl,omitempty" tf:"explicit_cache_control,omitempty"`

	ForwardingURL *ForwardingURLInitParameters `json:"forwardingUrl,omitempty" tf:"forwarding_url,omitempty"`

	HostHeaderOverride *string `json:"hostHeaderOverride,omitempty" tf:"host_header_override,omitempty"`

	IPGeolocation *string `json:"ipGeolocation,omitempty" tf:"ip_geolocation,omitempty"`

	Mirage *string `json:"mirage,omitempty" tf:"mirage,omitempty"`

	OpportunisticEncryption *string `json:"opportunisticEncryption,omitempty" tf:"opportunistic_encryption,omitempty"`

	OriginErrorPagePassThru *string `json:"originErrorPagePassThru,omitempty" tf:"origin_error_page_pass_thru,omitempty"`

	Polish *string `json:"polish,omitempty" tf:"polish,omitempty"`

	ResolveOverride *string `json:"resolveOverride,omitempty" tf:"resolve_override,omitempty"`

	RespectStrongEtag *string `json:"respectStrongEtag,omitempty" tf:"respect_strong_etag,omitempty"`

	ResponseBuffering *string `json:"responseBuffering,omitempty" tf:"response_buffering,omitempty"`

	RocketLoader *string `json:"rocketLoader,omitempty" tf:"rocket_loader,omitempty"`

	SSL *string `json:"ssl,omitempty" tf:"ssl,omitempty"`

	SecurityLevel *string `json:"securityLevel,omitempty" tf:"security_level,omitempty"`

	SortQueryStringForCache *string `json:"sortQueryStringForCache,omitempty" tf:"sort_query_string_for_cache,omitempty"`

	TrueClientIPHeader *string `json:"trueClientIpHeader,omitempty" tf:"true_client_ip_header,omitempty"`

	Waf *string `json:"waf,omitempty" tf:"waf,omitempty"`
}

type ActionsObservation struct {
	AlwaysUseHTTPS *bool `json:"alwaysUseHttps,omitempty" tf:"always_use_https,omitempty"`

	AutomaticHTTPSRewrites *string `json:"automaticHttpsRewrites,omitempty" tf:"automatic_https_rewrites,omitempty"`

	BrowserCacheTTL *float64 `json:"browserCacheTtl,omitempty" tf:"browser_cache_ttl,omitempty"`

	BrowserCheck *string `json:"browserCheck,omitempty" tf:"browser_check,omitempty"`

	BypassCacheOnCookie *string `json:"bypassCacheOnCookie,omitempty" tf:"bypass_cache_on_cookie,omitempty"`

	CacheByDeviceType *string `json:"cacheByDeviceType,omitempty" tf:"cache_by_device_type,omitempty"`

	CacheDeceptionArmor *string `json:"cacheDeceptionArmor,omitempty" tf:"cache_deception_armor,omitempty"`

	CacheKeyFields *CacheKeyFieldsObservation `json:"cacheKeyFields,omitempty" tf:"cache_key_fields,omitempty"`

	CacheLevel *string `json:"cacheLevel,omitempty" tf:"cache_level,omitempty"`

	CacheOnCookie *string `json:"cacheOnCookie,omitempty" tf:"cache_on_cookie,omitempty"`

	// +mapType=granular
	CacheTTLByStatus map[string]*string `json:"cacheTtlByStatus,omitempty" tf:"cache_ttl_by_status,omitempty"`

	DisableApps *bool `json:"disableApps,omitempty" tf:"disable_apps,omitempty"`

	DisablePerformance *bool `json:"disablePerformance,omitempty" tf:"disable_performance,omitempty"`

	DisableSecurity *bool `json:"disableSecurity,omitempty" tf:"disable_security,omitempty"`

	DisableZaraz *bool `json:"disableZaraz,omitempty" tf:"disable_zaraz,omitempty"`

	EdgeCacheTTL *float64 `json:"edgeCacheTtl,omitempty" tf:"edge_cache_ttl,omitempty"`

	EmailObfuscation *string `json:"emailObfuscation,omitempty" tf:"email_obfuscation,omitempty"`

	ExplicitCacheControl *string `json:"explicitCacheControl,omitempty" tf:"explicit_cache_control,omitempty"`

	ForwardingURL *ForwardingURLObservation `json:"forwardingUrl,omitempty" tf:"forwarding_url,omitempty"`

	HostHeaderOverride *string `json:"hostHeaderOverride,omitempty" tf:"host_header_override,omitempty"`

	IPGeolocation *string `json:"ipGeolocation,omitempty" tf:"ip_geolocation,omitempty"`

	Mirage *string `json:"mirage,omitempty" tf:"mirage,omitempty"`

	OpportunisticEncryption *string `json:"opportunisticEncryption,omitempty" tf:"opportunistic_encryption,omitempty"`

	OriginErrorPagePassThru *string `json:"originErrorPagePassThru,omitempty" tf:"origin_error_page_pass_thru,omitempty"`

	Polish *string `json:"polish,omitempty" tf:"polish,omitempty"`

	ResolveOverride *string `json:"resolveOverride,omitempty" tf:"resolve_override,omitempty"`

	RespectStrongEtag *string `json:"respectStrongEtag,omitempty" tf:"respect_strong_etag,omitempty"`

	ResponseBuffering *string `json:"responseBuffering,omitempty" tf:"response_buffering,omitempty"`

	RocketLoader *string `json:"rocketLoader,omitempty" tf:"rocket_loader,omitempty"`

	SSL *string `json:"ssl,omitempty" tf:"ssl,omitempty"`

	SecurityLevel *string `json:"securityLevel,omitempty" tf:"security_level,omitempty"`

	SortQueryStringForCache *string `json:"sortQueryStringForCache,omitempty" tf:"sort_query_string_for_cache,omitempty"`

	TrueClientIPHeader *string `json:"trueClientIpHeader,omitempty" tf:"true_client_ip_header,omitempty"`

	Waf *string `json:"waf,omitempty" tf:"waf,omitempty"`
}

type ActionsParameters struct {

	// +kubebuilder:validation:Optional
	AlwaysUseHTTPS *bool `json:"alwaysUseHttps,omitempty" tf:"always_use_https,omitempty"`

	// +kubebuilder:validation:Optional
	AutomaticHTTPSRewrites *string `json:"automaticHttpsRewrites,omitempty" tf:"automatic_https_rewrites,omitempty"`

	// +kubebuilder:validation:Optional
	BrowserCacheTTL *float64 `json:"browserCacheTtl,omitempty" tf:"browser_cache_ttl,omitempty"`

	// +kubebuilder:validation:Optional
	BrowserCheck *string `json:"browserCheck,omitempty" tf:"browser_check,omitempty"`

	// +kubebuilder:validation:Optional
	BypassCacheOnCookie *string `json:"bypassCacheOnCookie,omitempty" tf:"bypass_cache_on_cookie,omitempty"`

	// +kubebuilder:validation:Optional
	CacheByDeviceType *string `json:"cacheByDeviceType,omitempty" tf:"cache_by_device_type,omitempty"`

	// +kubebuilder:validation:Optional
	CacheDeceptionArmor *string `json:"cacheDeceptionArmor,omitempty" tf:"cache_deception_armor,omitempty"`

	// +kubebuilder:validation:Optional
	CacheKeyFields *CacheKeyFieldsParameters `json:"cacheKeyFields,omitempty" tf:"cache_key_fields,omitempty"`

	// +kubebuilder:validation:Optional
	CacheLevel *string `json:"cacheLevel,omitempty" tf:"cache_level,omitempty"`

	// +kubebuilder:validation:Optional
	CacheOnCookie *string `json:"cacheOnCookie,omitempty" tf:"cache_on_cookie,omitempty"`

	// +kubebuilder:validation:Optional
	// +mapType=granular
	CacheTTLByStatus map[string]*string `json:"cacheTtlByStatus,omitempty" tf:"cache_ttl_by_status,omitempty"`

	// +kubebuilder:validation:Optional
	DisableApps *bool `json:"disableApps,omitempty" tf:"disable_apps,omitempty"`

	// +kubebuilder:validation:Optional
	DisablePerformance *bool `json:"disablePerformance,omitempty" tf:"disable_performance,omitempty"`

	// +kubebuilder:validation:Optional
	DisableSecurity *bool `json:"disableSecurity,omitempty" tf:"disable_security,omitempty"`

	// +kubebuilder:validation:Optional
	DisableZaraz *bool `json:"disableZaraz,omitempty" tf:"disable_zaraz,omitempty"`

	// +kubebuilder:validation:Optional
	EdgeCacheTTL *float64 `json:"edgeCacheTtl,omitempty" tf:"edge_cache_ttl,omitempty"`

	// +kubebuilder:validation:Optional
	EmailObfuscation *string `json:"emailObfuscation,omitempty" tf:"email_obfuscation,omitempty"`

	// +kubebuilder:validation:Optional
	ExplicitCacheControl *string `json:"explicitCacheControl,omitempty" tf:"explicit_cache_control,omitempty"`

	// +kubebuilder:validation:Optional
	ForwardingURL *ForwardingURLParameters `json:"forwardingUrl,omitempty" tf:"forwarding_url,omitempty"`

	// +kubebuilder:validation:Optional
	HostHeaderOverride *string `json:"hostHeaderOverride,omitempty" tf:"host_header_override,omitempty"`

	// +kubebuilder:validation:Optional
	IPGeolocation *string `json:"ipGeolocation,omitempty" tf:"ip_geolocation,omitempty"`

	// +kubebuilder:validation:Optional
	Mirage *string `json:"mirage,omitempty" tf:"mirage,omitempty"`

	// +kubebuilder:validation:Optional
	OpportunisticEncryption *string `json:"opportunisticEncryption,omitempty" tf:"opportunistic_encryption,omitempty"`

	// +kubebuilder:validation:Optional
	OriginErrorPagePassThru *string `json:"originErrorPagePassThru,omitempty" tf:"origin_error_page_pass_thru,omitempty"`

	// +kubebuilder:validation:Optional
	Polish *string `json:"polish,omitempty" tf:"polish,omitempty"`

	// +kubebuilder:validation:Optional
	ResolveOverride *string `json:"resolveOverride,omitempty" tf:"resolve_override,omitempty"`

	// +kubebuilder:validation:Optional
	RespectStrongEtag *string `json:"respectStrongEtag,omitempty" tf:"respect_strong_etag,omitempty"`

	// +kubebuilder:validation:Optional
	ResponseBuffering *string `json:"responseBuffering,omitempty" tf:"response_buffering,omitempty"`

	// +kubebuilder:validation:Optional
	RocketLoader *string `json:"rocketLoader,omitempty" tf:"rocket_loader,omitempty"`

	// +kubebuilder:validation:Optional
	SSL *string `json:"ssl,omitempty" tf:"ssl,omitempty"`

	// +kubebuilder:validation:Optional
	SecurityLevel *string `json:"securityLevel,omitempty" tf:"security_level,omitempty"`

	// +kubebuilder:validation:Optional
	SortQueryStringForCache *string `json:"sortQueryStringForCache,omitempty" tf:"sort_query_string_for_cache,omitempty"`

	// +kubebuilder:validation:Optional
	TrueClientIPHeader *string `json:"trueClientIpHeader,omitempty" tf:"true_client_ip_header,omitempty"`

	// +kubebuilder:validation:Optional
	Waf *string `json:"waf,omitempty" tf:"waf,omitempty"`
}

type CacheKeyFieldsInitParameters struct {
	Cookie *CookieInitParameters `json:"cookie,omitempty" tf:"cookie,omitempty"`

	Header *HeaderInitParameters `json:"header,omitempty" tf:"header,omitempty"`

	Host *HostInitParameters `json:"host,omitempty" tf:"host,omitempty"`

	QueryString *QueryStringInitParameters `json:"queryString,omitempty" tf:"query_string,omitempty"`

	User *UserInitParameters `json:"user,omitempty" tf:"user,omitempty"`
}

type CacheKeyFieldsObservation struct {
	Cookie *CookieObservation `json:"cookie,omitempty" tf:"cookie,omitempty"`

	Header *HeaderObservation `json:"header,omitempty" tf:"header,omitempty"`

	Host *HostObservation `json:"host,omitempty" tf:"host,omitempty"`

	QueryString *QueryStringObservation `json:"queryString,omitempty" tf:"query_string,omitempty"`

	User *UserObservation `json:"user,omitempty" tf:"user,omitempty"`
}

type CacheKeyFieldsParameters struct {

	// +kubebuilder:validation:Optional
	Cookie *CookieParameters `json:"cookie,omitempty" tf:"cookie,omitempty"`

	// +kubebuilder:validation:Optional
	Header *HeaderParameters `json:"header,omitempty" tf:"header,omitempty"`

	// +kubebuilder:validation:Optional
	Host *HostParameters `json:"host,omitempty" tf:"host,omitempty"`

	// +kubebuilder:validation:Optional
	QueryString *QueryStringParameters `json:"queryString,omitempty" tf:"query_string,omitempty"`

	// +kubebuilder:validation:Optional
	User *UserParameters `json:"user,omitempty" tf:"user,omitempty"`
}

type CookieInitParameters struct {
	CheckPresence []*string `json:"checkPresence,omitempty" tf:"check_presence,omitempty"`

	Include []*string `json:"include,omitempty" tf:"include,omitempty"`
}

type CookieObservation struct {
	CheckPresence []*string `json:"checkPresence,omitempty" tf:"check_presence,omitempty"`

	Include []*string `json:"include,omitempty" tf:"include,omitempty"`
}

type CookieParameters struct {

	// +kubebuilder:validation:Optional
	CheckPresence []*string `json:"checkPresence,omitempty" tf:"check_presence,omitempty"`

	// +kubebuilder:validation:Optional
	Include []*string `json:"include,omitempty" tf:"include,omitempty"`
}

type ForwardingURLInitParameters struct {
	StatusCode *float64 `json:"statusCode,omitempty" tf:"status_code,omitempty"`

	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type ForwardingURLObservation struct {
	StatusCode *float64 `json:"statusCode,omitempty" tf:"status_code,omitempty"`

	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type ForwardingURLParameters struct {

	// +kubebuilder:validation:Optional
	StatusCode *float64 `json:"statusCode" tf:"status_code,omitempty"`

	// +kubebuilder:validation:Optional
	URL *string `json:"url" tf:"url,omitempty"`
}

type HeaderInitParameters struct {
	CheckPresence []*string `json:"checkPresence,omitempty" tf:"check_presence,omitempty"`

	Exclude []*string `json:"exclude,omitempty" tf:"exclude,omitempty"`

	Include []*string `json:"include,omitempty" tf:"include,omitempty"`
}

type HeaderObservation struct {
	CheckPresence []*string `json:"checkPresence,omitempty" tf:"check_presence,omitempty"`

	Exclude []*string `json:"exclude,omitempty" tf:"exclude,omitempty"`

	Include []*string `json:"include,omitempty" tf:"include,omitempty"`
}

type HeaderParameters struct {

	// +kubebuilder:validation:Optional
	CheckPresence []*string `json:"checkPresence,omitempty" tf:"check_presence,omitempty"`

	// +kubebuilder:validation:Optional
	Exclude []*string `json:"exclude,omitempty" tf:"exclude,omitempty"`

	// +kubebuilder:validation:Optional
	Include []*string `json:"include,omitempty" tf:"include,omitempty"`
}

type HostInitParameters struct {
	Resolved *bool `json:"resolved,omitempty" tf:"resolved,omitempty"`
}

type HostObservation struct {
	Resolved *bool `json:"resolved,omitempty" tf:"resolved,omitempty"`
}

type HostParameters struct {

	// +kubebuilder:validation:Optional
	Resolved *bool `json:"resolved,omitempty" tf:"resolved,omitempty"`
}

type QueryStringInitParameters struct {
	Exclude []*string `json:"exclude,omitempty" tf:"exclude,omitempty"`

	Include []*string `json:"include,omitempty" tf:"include,omitempty"`
}

type QueryStringObservation struct {
	Exclude []*string `json:"exclude,omitempty" tf:"exclude,omitempty"`

	Include []*string `json:"include,omitempty" tf:"include,omitempty"`
}

type QueryStringParameters struct {

	// +kubebuilder:validation:Optional
	Exclude []*string `json:"exclude,omitempty" tf:"exclude,omitempty"`

	// +kubebuilder:validation:Optional
	Include []*string `json:"include,omitempty" tf:"include,omitempty"`
}

type RuleInitParameters struct {
	Actions *ActionsInitParameters `json:"actions,omitempty" tf:"actions,omitempty"`

	// The priority of the rule, used to define which Page Rule is processed
	// over another. A higher number indicates a higher priority. For example,
	// if you have a catch-all Page Rule (rule A: `/images/*`) but want a more
	// specific Page Rule to take precedence (rule B: `/images/special/*`),
	// specify a higher priority for rule B so it overrides rule A.
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// The status of the Page Rule.
	// Available values: "active", "disabled".
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	Target *string `json:"target,omitempty" tf:"target,omitempty"`

	// Identifier.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type RuleObservation struct {
	Actions *ActionsObservation `json:"actions,omitempty" tf:"actions,omitempty"`

	// The timestamp of when the Page Rule was created.
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The timestamp of when the Page Rule was last modified.
	ModifiedOn *string `json:"modifiedOn,omitempty" tf:"modified_on,omitempty"`

	// The priority of the rule, used to define which Page Rule is processed
	// over another. A higher number indicates a higher priority. For example,
	// if you have a catch-all Page Rule (rule A: `/images/*`) but want a more
	// specific Page Rule to take precedence (rule B: `/images/special/*`),
	// specify a higher priority for rule B so it overrides rule A.
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// The status of the Page Rule.
	// Available values: "active", "disabled".
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	Target *string `json:"target,omitempty" tf:"target,omitempty"`

	// Identifier.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type RuleParameters struct {

	// +kubebuilder:validation:Optional
	Actions *ActionsParameters `json:"actions,omitempty" tf:"actions,omitempty"`

	// The priority of the rule, used to define which Page Rule is processed
	// over another. A higher number indicates a higher priority. For example,
	// if you have a catch-all Page Rule (rule A: `/images/*`) but want a more
	// specific Page Rule to take precedence (rule B: `/images/special/*`),
	// specify a higher priority for rule B so it overrides rule A.
	// +kubebuilder:validation:Optional
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// The status of the Page Rule.
	// Available values: "active", "disabled".
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// +kubebuilder:validation:Optional
	Target *string `json:"target,omitempty" tf:"target,omitempty"`

	// Identifier.
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type UserInitParameters struct {
	DeviceType *bool `json:"deviceType,omitempty" tf:"device_type,omitempty"`

	Geo *bool `json:"geo,omitempty" tf:"geo,omitempty"`

	Lang *bool `json:"lang,omitempty" tf:"lang,omitempty"`
}

type UserObservation struct {
	DeviceType *bool `json:"deviceType,omitempty" tf:"device_type,omitempty"`

	Geo *bool `json:"geo,omitempty" tf:"geo,omitempty"`

	Lang *bool `json:"lang,omitempty" tf:"lang,omitempty"`
}

type UserParameters struct {

	// +kubebuilder:validation:Optional
	DeviceType *bool `json:"deviceType,omitempty" tf:"device_type,omitempty"`

	// +kubebuilder:validation:Optional
	Geo *bool `json:"geo,omitempty" tf:"geo,omitempty"`

	// +kubebuilder:validation:Optional
	Lang *bool `json:"lang,omitempty" tf:"lang,omitempty"`
}

// RuleSpec defines the desired state of Rule
type RuleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RuleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RuleInitParameters `json:"initProvider,omitempty"`
}

// RuleStatus defines the observed state of Rule.
type RuleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Rule is the Schema for the Rules API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type Rule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.actions) || (has(self.initProvider) && has(self.initProvider.actions))",message="spec.forProvider.actions is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.target) || (has(self.initProvider) && has(self.initProvider.target))",message="spec.forProvider.target is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zoneId) || (has(self.initProvider) && has(self.initProvider.zoneId))",message="spec.forProvider.zoneId is a required parameter"
	Spec   RuleSpec   `json:"spec"`
	Status RuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RuleList contains a list of Rules
type RuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Rule `json:"items"`
}

// Repository type metadata.
var (
	Rule_Kind             = "Rule"
	Rule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Rule_Kind}.String()
	Rule_KindAPIVersion   = Rule_Kind + "." + CRDGroupVersion.String()
	Rule_GroupVersionKind = CRDGroupVersion.WithKind(Rule_Kind)
)

func init() {
	SchemeBuilder.Register(&Rule{}, &RuleList{})
}
