// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type DesktopReportInitParameters struct {
}

type DesktopReportObservation struct {

	// Cumulative Layout Shift.
	Cls *float64 `json:"cls,omitempty" tf:"cls,omitempty"`

	// The type of device.
	// Available values: "DESKTOP", "MOBILE".
	DeviceType *string `json:"deviceType,omitempty" tf:"device_type,omitempty"`

	Error *ErrorObservation `json:"error,omitempty" tf:"error,omitempty"`

	// First Contentful Paint.
	Fcp *float64 `json:"fcp,omitempty" tf:"fcp,omitempty"`

	// The URL to the full Lighthouse JSON report.
	JSONReportURL *string `json:"jsonReportUrl,omitempty" tf:"json_report_url,omitempty"`

	// Largest Contentful Paint.
	Lcp *float64 `json:"lcp,omitempty" tf:"lcp,omitempty"`

	// The Lighthouse performance score.
	PerformanceScore *float64 `json:"performanceScore,omitempty" tf:"performance_score,omitempty"`

	// Speed Index.
	Si *float64 `json:"si,omitempty" tf:"si,omitempty"`

	// The state of the Lighthouse report.
	// Available values: "RUNNING", "COMPLETE", "FAILED".
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// Total Blocking Time.
	Tbt *float64 `json:"tbt,omitempty" tf:"tbt,omitempty"`

	// Time To First Byte.
	Ttfb *float64 `json:"ttfb,omitempty" tf:"ttfb,omitempty"`

	// Time To Interactive.
	Tti *float64 `json:"tti,omitempty" tf:"tti,omitempty"`
}

type DesktopReportParameters struct {
}

type ErrorInitParameters struct {
}

type ErrorObservation struct {

	// The error code of the Lighthouse result.
	// Available values: "NOT_REACHABLE", "DNS_FAILURE", "NOT_HTML", "LIGHTHOUSE_TIMEOUT", "UNKNOWN".
	Code *string `json:"code,omitempty" tf:"code,omitempty"`

	// Detailed error message.
	Detail *string `json:"detail,omitempty" tf:"detail,omitempty"`

	// The final URL displayed to the user.
	FinalDisplayedURL *string `json:"finalDisplayedUrl,omitempty" tf:"final_displayed_url,omitempty"`
}

type ErrorParameters struct {
}

type MobileReportErrorInitParameters struct {
}

type MobileReportErrorObservation struct {

	// The error code of the Lighthouse result.
	// Available values: "NOT_REACHABLE", "DNS_FAILURE", "NOT_HTML", "LIGHTHOUSE_TIMEOUT", "UNKNOWN".
	Code *string `json:"code,omitempty" tf:"code,omitempty"`

	// Detailed error message.
	Detail *string `json:"detail,omitempty" tf:"detail,omitempty"`

	// The final URL displayed to the user.
	FinalDisplayedURL *string `json:"finalDisplayedUrl,omitempty" tf:"final_displayed_url,omitempty"`
}

type MobileReportErrorParameters struct {
}

type MobileReportInitParameters struct {
}

type MobileReportObservation struct {

	// Cumulative Layout Shift.
	Cls *float64 `json:"cls,omitempty" tf:"cls,omitempty"`

	// The type of device.
	// Available values: "DESKTOP", "MOBILE".
	DeviceType *string `json:"deviceType,omitempty" tf:"device_type,omitempty"`

	Error *MobileReportErrorObservation `json:"error,omitempty" tf:"error,omitempty"`

	// First Contentful Paint.
	Fcp *float64 `json:"fcp,omitempty" tf:"fcp,omitempty"`

	// The URL to the full Lighthouse JSON report.
	JSONReportURL *string `json:"jsonReportUrl,omitempty" tf:"json_report_url,omitempty"`

	// Largest Contentful Paint.
	Lcp *float64 `json:"lcp,omitempty" tf:"lcp,omitempty"`

	// The Lighthouse performance score.
	PerformanceScore *float64 `json:"performanceScore,omitempty" tf:"performance_score,omitempty"`

	// Speed Index.
	Si *float64 `json:"si,omitempty" tf:"si,omitempty"`

	// The state of the Lighthouse report.
	// Available values: "RUNNING", "COMPLETE", "FAILED".
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// Total Blocking Time.
	Tbt *float64 `json:"tbt,omitempty" tf:"tbt,omitempty"`

	// Time To First Byte.
	Ttfb *float64 `json:"ttfb,omitempty" tf:"ttfb,omitempty"`

	// Time To Interactive.
	Tti *float64 `json:"tti,omitempty" tf:"tti,omitempty"`
}

type MobileReportParameters struct {
}

type RegionInitParameters struct {
}

type RegionObservation struct {
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// A test region.
	// Available values: "asia-east1", "asia-northeast1", "asia-northeast2", "asia-south1", "asia-southeast1", "australia-southeast1", "europe-north1", "europe-southwest1", "europe-west1", "europe-west2", "europe-west3", "europe-west4", "europe-west8", "europe-west9", "me-west1", "southamerica-east1", "us-central1", "us-east1", "us-east4", "us-south1", "us-west1".
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type RegionParameters struct {
}

type ScheduleInitParameters struct {
}

type ScheduleObservation struct {

	// The frequency of the test.
	// Available values: "DAILY", "WEEKLY".
	Frequency *string `json:"frequency,omitempty" tf:"frequency,omitempty"`

	// A test region.
	// Available values: "asia-east1", "asia-northeast1", "asia-northeast2", "asia-south1", "asia-southeast1", "australia-southeast1", "europe-north1", "europe-southwest1", "europe-west1", "europe-west2", "europe-west3", "europe-west4", "europe-west8", "europe-west9", "me-west1", "southamerica-east1", "us-central1", "us-east1", "us-east4", "us-south1", "us-west1".
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// A URL.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type ScheduleParameters struct {
}

type ScheduledTestInitParameters struct {

	// A URL.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// Identifier.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type ScheduledTestObservation struct {

	// The frequency of the test.
	// Available values: "DAILY", "WEEKLY".
	Frequency *string `json:"frequency,omitempty" tf:"frequency,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A test region.
	// Available values: "asia-east1", "asia-northeast1", "asia-northeast2", "asia-south1", "asia-southeast1", "australia-southeast1", "europe-north1", "europe-southwest1", "europe-west1", "europe-west2", "europe-west3", "europe-west4", "europe-west8", "europe-west9", "me-west1", "southamerica-east1", "us-central1", "us-east1", "us-east4", "us-south1", "us-west1".
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	Schedule *ScheduleObservation `json:"schedule,omitempty" tf:"schedule,omitempty"`

	Test *TestObservation `json:"test,omitempty" tf:"test,omitempty"`

	// A URL.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// Identifier.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type ScheduledTestParameters struct {

	// A URL.
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// Identifier.
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type TestInitParameters struct {
}

type TestObservation struct {
	Date *string `json:"date,omitempty" tf:"date,omitempty"`

	DesktopReport *DesktopReportObservation `json:"desktopReport,omitempty" tf:"desktop_report,omitempty"`

	// UUID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	MobileReport *MobileReportObservation `json:"mobileReport,omitempty" tf:"mobile_report,omitempty"`

	Region *RegionObservation `json:"region,omitempty" tf:"region,omitempty"`

	// The frequency of the test.
	// Available values: "DAILY", "WEEKLY".
	ScheduleFrequency *string `json:"scheduleFrequency,omitempty" tf:"schedule_frequency,omitempty"`

	// A URL.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type TestParameters struct {
}

// ScheduledTestSpec defines the desired state of ScheduledTest
type ScheduledTestSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ScheduledTestParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ScheduledTestInitParameters `json:"initProvider,omitempty"`
}

// ScheduledTestStatus defines the observed state of ScheduledTest.
type ScheduledTestStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ScheduledTestObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ScheduledTest is the Schema for the ScheduledTests API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type ScheduledTest struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.url) || (has(self.initProvider) && has(self.initProvider.url))",message="spec.forProvider.url is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zoneId) || (has(self.initProvider) && has(self.initProvider.zoneId))",message="spec.forProvider.zoneId is a required parameter"
	Spec   ScheduledTestSpec   `json:"spec"`
	Status ScheduledTestStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ScheduledTestList contains a list of ScheduledTests
type ScheduledTestList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ScheduledTest `json:"items"`
}

// Repository type metadata.
var (
	ScheduledTest_Kind             = "ScheduledTest"
	ScheduledTest_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ScheduledTest_Kind}.String()
	ScheduledTest_KindAPIVersion   = ScheduledTest_Kind + "." + CRDGroupVersion.String()
	ScheduledTest_GroupVersionKind = CRDGroupVersion.WithKind(ScheduledTest_Kind)
)

func init() {
	SchemeBuilder.Register(&ScheduledTest{}, &ScheduledTestList{})
}
