apiVersion: custom.cloudflare.crossplane.io/v1alpha1
kind: Pages
metadata:
  annotations:
    meta.upbound.io/example-id: custom/v1alpha1/pages
  labels:
    testing.upbound.io/example-name: example_custom_pages
  name: example-custom-pages
spec:
  forProvider:
    identifier: ratelimit_block
    state: default
    url: http://www.example.com
    zoneId: zone_id
