// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type CredentialsInitParameters struct {
	Keys []KeysInitParameters `json:"keys,omitempty" tf:"keys,omitempty"`
}

type CredentialsObservation struct {
	Keys []KeysObservation `json:"keys,omitempty" tf:"keys,omitempty"`
}

type CredentialsParameters struct {

	// +kubebuilder:validation:Optional
	Keys []KeysParameters `json:"keys" tf:"keys,omitempty"`
}

type KeysInitParameters struct {

	// Algorithm
	// Available values: "RS256", "RS384", "RS512", "PS256", "PS384", "PS512", "ES256", "ES384".
	Alg *string `json:"alg,omitempty" tf:"alg,omitempty"`

	// Curve
	// Available values: "P-256", "P-384".
	Crv *string `json:"crv,omitempty" tf:"crv,omitempty"`

	// RSA exponent
	E *string `json:"e,omitempty" tf:"e,omitempty"`

	// Key ID
	Kid *string `json:"kid,omitempty" tf:"kid,omitempty"`

	// Key Type
	// Available values: "RSA", "EC".
	Kty *string `json:"kty,omitempty" tf:"kty,omitempty"`

	// RSA modulus
	N *string `json:"n,omitempty" tf:"n,omitempty"`

	// X EC coordinate
	X *string `json:"x,omitempty" tf:"x,omitempty"`

	// Y EC coordinate
	Y *string `json:"y,omitempty" tf:"y,omitempty"`
}

type KeysObservation struct {

	// Algorithm
	// Available values: "RS256", "RS384", "RS512", "PS256", "PS384", "PS512", "ES256", "ES384".
	Alg *string `json:"alg,omitempty" tf:"alg,omitempty"`

	// Curve
	// Available values: "P-256", "P-384".
	Crv *string `json:"crv,omitempty" tf:"crv,omitempty"`

	// RSA exponent
	E *string `json:"e,omitempty" tf:"e,omitempty"`

	// Key ID
	Kid *string `json:"kid,omitempty" tf:"kid,omitempty"`

	// Key Type
	// Available values: "RSA", "EC".
	Kty *string `json:"kty,omitempty" tf:"kty,omitempty"`

	// RSA modulus
	N *string `json:"n,omitempty" tf:"n,omitempty"`

	// X EC coordinate
	X *string `json:"x,omitempty" tf:"x,omitempty"`

	// Y EC coordinate
	Y *string `json:"y,omitempty" tf:"y,omitempty"`
}

type KeysParameters struct {

	// Algorithm
	// Available values: "RS256", "RS384", "RS512", "PS256", "PS384", "PS512", "ES256", "ES384".
	// +kubebuilder:validation:Optional
	Alg *string `json:"alg" tf:"alg,omitempty"`

	// Curve
	// Available values: "P-256", "P-384".
	// +kubebuilder:validation:Optional
	Crv *string `json:"crv,omitempty" tf:"crv,omitempty"`

	// RSA exponent
	// +kubebuilder:validation:Optional
	E *string `json:"e,omitempty" tf:"e,omitempty"`

	// Key ID
	// +kubebuilder:validation:Optional
	Kid *string `json:"kid" tf:"kid,omitempty"`

	// Key Type
	// Available values: "RSA", "EC".
	// +kubebuilder:validation:Optional
	Kty *string `json:"kty" tf:"kty,omitempty"`

	// RSA modulus
	// +kubebuilder:validation:Optional
	N *string `json:"n,omitempty" tf:"n,omitempty"`

	// X EC coordinate
	// +kubebuilder:validation:Optional
	X *string `json:"x,omitempty" tf:"x,omitempty"`

	// Y EC coordinate
	// +kubebuilder:validation:Optional
	Y *string `json:"y,omitempty" tf:"y,omitempty"`
}

type ValidationConfigInitParameters struct {
	Credentials *CredentialsInitParameters `json:"credentials,omitempty" tf:"credentials,omitempty"`

	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	Title *string `json:"title,omitempty" tf:"title,omitempty"`

	TokenSources []*string `json:"tokenSources,omitempty" tf:"token_sources,omitempty"`

	// Available values: "JWT".
	TokenType *string `json:"tokenType,omitempty" tf:"token_type,omitempty"`

	// Identifier.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type ValidationConfigObservation struct {
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	Credentials *CredentialsObservation `json:"credentials,omitempty" tf:"credentials,omitempty"`

	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	Title *string `json:"title,omitempty" tf:"title,omitempty"`

	TokenSources []*string `json:"tokenSources,omitempty" tf:"token_sources,omitempty"`

	// Available values: "JWT".
	TokenType *string `json:"tokenType,omitempty" tf:"token_type,omitempty"`

	// Identifier.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type ValidationConfigParameters struct {

	// +kubebuilder:validation:Optional
	Credentials *CredentialsParameters `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// +kubebuilder:validation:Optional
	Title *string `json:"title,omitempty" tf:"title,omitempty"`

	// +kubebuilder:validation:Optional
	TokenSources []*string `json:"tokenSources,omitempty" tf:"token_sources,omitempty"`

	// Available values: "JWT".
	// +kubebuilder:validation:Optional
	TokenType *string `json:"tokenType,omitempty" tf:"token_type,omitempty"`

	// Identifier.
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

// ValidationConfigSpec defines the desired state of ValidationConfig
type ValidationConfigSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ValidationConfigParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ValidationConfigInitParameters `json:"initProvider,omitempty"`
}

// ValidationConfigStatus defines the observed state of ValidationConfig.
type ValidationConfigStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ValidationConfigObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ValidationConfig is the Schema for the ValidationConfigs API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type ValidationConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.credentials) || (has(self.initProvider) && has(self.initProvider.credentials))",message="spec.forProvider.credentials is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.description) || (has(self.initProvider) && has(self.initProvider.description))",message="spec.forProvider.description is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.title) || (has(self.initProvider) && has(self.initProvider.title))",message="spec.forProvider.title is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.tokenSources) || (has(self.initProvider) && has(self.initProvider.tokenSources))",message="spec.forProvider.tokenSources is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.tokenType) || (has(self.initProvider) && has(self.initProvider.tokenType))",message="spec.forProvider.tokenType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zoneId) || (has(self.initProvider) && has(self.initProvider.zoneId))",message="spec.forProvider.zoneId is a required parameter"
	Spec   ValidationConfigSpec   `json:"spec"`
	Status ValidationConfigStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ValidationConfigList contains a list of ValidationConfigs
type ValidationConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ValidationConfig `json:"items"`
}

// Repository type metadata.
var (
	ValidationConfig_Kind             = "ValidationConfig"
	ValidationConfig_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ValidationConfig_Kind}.String()
	ValidationConfig_KindAPIVersion   = ValidationConfig_Kind + "." + CRDGroupVersion.String()
	ValidationConfig_GroupVersionKind = CRDGroupVersion.WithKind(ValidationConfig_Kind)
)

func init() {
	SchemeBuilder.Register(&ValidationConfig{}, &ValidationConfigList{})
}
