// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ApprovalGroupsInitParameters struct {

	// The number of approvals needed to obtain access.
	ApprovalsNeeded *float64 `json:"approvalsNeeded,omitempty" tf:"approvals_needed,omitempty"`

	// A list of emails that can approve the access request.
	EmailAddresses []*string `json:"emailAddresses,omitempty" tf:"email_addresses,omitempty"`

	// The UUID of an re-usable email list.
	EmailListUUID *string `json:"emailListUuid,omitempty" tf:"email_list_uuid,omitempty"`
}

type ApprovalGroupsObservation struct {

	// The number of approvals needed to obtain access.
	ApprovalsNeeded *float64 `json:"approvalsNeeded,omitempty" tf:"approvals_needed,omitempty"`

	// A list of emails that can approve the access request.
	EmailAddresses []*string `json:"emailAddresses,omitempty" tf:"email_addresses,omitempty"`

	// The UUID of an re-usable email list.
	EmailListUUID *string `json:"emailListUuid,omitempty" tf:"email_list_uuid,omitempty"`
}

type ApprovalGroupsParameters struct {

	// The number of approvals needed to obtain access.
	// +kubebuilder:validation:Optional
	ApprovalsNeeded *float64 `json:"approvalsNeeded" tf:"approvals_needed,omitempty"`

	// A list of emails that can approve the access request.
	// +kubebuilder:validation:Optional
	EmailAddresses []*string `json:"emailAddresses,omitempty" tf:"email_addresses,omitempty"`

	// The UUID of an re-usable email list.
	// +kubebuilder:validation:Optional
	EmailListUUID *string `json:"emailListUuid,omitempty" tf:"email_list_uuid,omitempty"`
}

type TrustAccessPolicyExcludeAnyValidServiceTokenInitParameters struct {
}

type TrustAccessPolicyExcludeAnyValidServiceTokenObservation struct {
}

type TrustAccessPolicyExcludeAnyValidServiceTokenParameters struct {
}

type TrustAccessPolicyExcludeAuthContextInitParameters struct {

	// The ACID of an Authentication context.
	AcID *string `json:"acId,omitempty" tf:"ac_id,omitempty"`

	// The ID of an Authentication context.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of your Azure identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyExcludeAuthContextObservation struct {

	// The ACID of an Authentication context.
	AcID *string `json:"acId,omitempty" tf:"ac_id,omitempty"`

	// The ID of an Authentication context.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of your Azure identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyExcludeAuthContextParameters struct {

	// The ACID of an Authentication context.
	// +kubebuilder:validation:Optional
	AcID *string `json:"acId" tf:"ac_id,omitempty"`

	// The ID of an Authentication context.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// The ID of your Azure identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyExcludeAuthMethodInitParameters struct {

	// The type of authentication method https://datatracker.ietf.org/doc/html/rfc8176#section-2.
	AuthMethod *string `json:"authMethod,omitempty" tf:"auth_method,omitempty"`
}

type TrustAccessPolicyExcludeAuthMethodObservation struct {

	// The type of authentication method https://datatracker.ietf.org/doc/html/rfc8176#section-2.
	AuthMethod *string `json:"authMethod,omitempty" tf:"auth_method,omitempty"`
}

type TrustAccessPolicyExcludeAuthMethodParameters struct {

	// The type of authentication method https://datatracker.ietf.org/doc/html/rfc8176#section-2.
	// +kubebuilder:validation:Optional
	AuthMethod *string `json:"authMethod" tf:"auth_method,omitempty"`
}

type TrustAccessPolicyExcludeAzureAdInitParameters struct {

	// The ID of an Azure group.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of your Azure identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyExcludeAzureAdObservation struct {

	// The ID of an Azure group.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of your Azure identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyExcludeAzureAdParameters struct {

	// The ID of an Azure group.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// The ID of your Azure identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyExcludeCertificateInitParameters struct {
}

type TrustAccessPolicyExcludeCertificateObservation struct {
}

type TrustAccessPolicyExcludeCertificateParameters struct {
}

type TrustAccessPolicyExcludeCommonNameInitParameters struct {

	// The common name to match.
	CommonName *string `json:"commonName,omitempty" tf:"common_name,omitempty"`
}

type TrustAccessPolicyExcludeCommonNameObservation struct {

	// The common name to match.
	CommonName *string `json:"commonName,omitempty" tf:"common_name,omitempty"`
}

type TrustAccessPolicyExcludeCommonNameParameters struct {

	// The common name to match.
	// +kubebuilder:validation:Optional
	CommonName *string `json:"commonName" tf:"common_name,omitempty"`
}

type TrustAccessPolicyExcludeDevicePostureInitParameters struct {

	// The ID of a device posture integration.
	IntegrationUID *string `json:"integrationUid,omitempty" tf:"integration_uid,omitempty"`
}

type TrustAccessPolicyExcludeDevicePostureObservation struct {

	// The ID of a device posture integration.
	IntegrationUID *string `json:"integrationUid,omitempty" tf:"integration_uid,omitempty"`
}

type TrustAccessPolicyExcludeDevicePostureParameters struct {

	// The ID of a device posture integration.
	// +kubebuilder:validation:Optional
	IntegrationUID *string `json:"integrationUid" tf:"integration_uid,omitempty"`
}

type TrustAccessPolicyExcludeEmailDomainInitParameters struct {

	// The email domain to match.
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`
}

type TrustAccessPolicyExcludeEmailDomainObservation struct {

	// The email domain to match.
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`
}

type TrustAccessPolicyExcludeEmailDomainParameters struct {

	// The email domain to match.
	// +kubebuilder:validation:Optional
	Domain *string `json:"domain" tf:"domain,omitempty"`
}

type TrustAccessPolicyExcludeEmailInitParameters struct {

	// The email of the user.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type TrustAccessPolicyExcludeEmailListInitParameters struct {

	// The ID of a previously created email list.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TrustAccessPolicyExcludeEmailListObservation struct {

	// The ID of a previously created email list.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TrustAccessPolicyExcludeEmailListParameters struct {

	// The ID of a previously created email list.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type TrustAccessPolicyExcludeEmailObservation struct {

	// The email of the user.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type TrustAccessPolicyExcludeEmailParameters struct {

	// The email of the user.
	// +kubebuilder:validation:Optional
	Email *string `json:"email" tf:"email,omitempty"`
}

type TrustAccessPolicyExcludeEveryoneInitParameters struct {
}

type TrustAccessPolicyExcludeEveryoneObservation struct {
}

type TrustAccessPolicyExcludeEveryoneParameters struct {
}

type TrustAccessPolicyExcludeExternalEvaluationInitParameters struct {

	// The API endpoint containing your business logic.
	EvaluateURL *string `json:"evaluateUrl,omitempty" tf:"evaluate_url,omitempty"`

	// The API endpoint containing the key that Access uses to verify that the response came from your API.
	KeysURL *string `json:"keysUrl,omitempty" tf:"keys_url,omitempty"`
}

type TrustAccessPolicyExcludeExternalEvaluationObservation struct {

	// The API endpoint containing your business logic.
	EvaluateURL *string `json:"evaluateUrl,omitempty" tf:"evaluate_url,omitempty"`

	// The API endpoint containing the key that Access uses to verify that the response came from your API.
	KeysURL *string `json:"keysUrl,omitempty" tf:"keys_url,omitempty"`
}

type TrustAccessPolicyExcludeExternalEvaluationParameters struct {

	// The API endpoint containing your business logic.
	// +kubebuilder:validation:Optional
	EvaluateURL *string `json:"evaluateUrl" tf:"evaluate_url,omitempty"`

	// The API endpoint containing the key that Access uses to verify that the response came from your API.
	// +kubebuilder:validation:Optional
	KeysURL *string `json:"keysUrl" tf:"keys_url,omitempty"`
}

type TrustAccessPolicyExcludeGeoInitParameters struct {

	// The country code that should be matched.
	CountryCode *string `json:"countryCode,omitempty" tf:"country_code,omitempty"`
}

type TrustAccessPolicyExcludeGeoObservation struct {

	// The country code that should be matched.
	CountryCode *string `json:"countryCode,omitempty" tf:"country_code,omitempty"`
}

type TrustAccessPolicyExcludeGeoParameters struct {

	// The country code that should be matched.
	// +kubebuilder:validation:Optional
	CountryCode *string `json:"countryCode" tf:"country_code,omitempty"`
}

type TrustAccessPolicyExcludeGithubOrganizationInitParameters struct {

	// The ID of your Github identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// The name of the organization.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of the team
	Team *string `json:"team,omitempty" tf:"team,omitempty"`
}

type TrustAccessPolicyExcludeGithubOrganizationObservation struct {

	// The ID of your Github identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// The name of the organization.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of the team
	Team *string `json:"team,omitempty" tf:"team,omitempty"`
}

type TrustAccessPolicyExcludeGithubOrganizationParameters struct {

	// The ID of your Github identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId" tf:"identity_provider_id,omitempty"`

	// The name of the organization.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// The name of the team
	// +kubebuilder:validation:Optional
	Team *string `json:"team,omitempty" tf:"team,omitempty"`
}

type TrustAccessPolicyExcludeGroupInitParameters struct {

	// The ID of a previously created Access group.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TrustAccessPolicyExcludeGroupObservation struct {

	// The ID of a previously created Access group.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TrustAccessPolicyExcludeGroupParameters struct {

	// The ID of a previously created Access group.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type TrustAccessPolicyExcludeGsuiteInitParameters struct {

	// The email of the Google Workspace group.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// The ID of your Google Workspace identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyExcludeGsuiteObservation struct {

	// The email of the Google Workspace group.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// The ID of your Google Workspace identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyExcludeGsuiteParameters struct {

	// The email of the Google Workspace group.
	// +kubebuilder:validation:Optional
	Email *string `json:"email" tf:"email,omitempty"`

	// The ID of your Google Workspace identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyExcludeIPInitParameters struct {

	// An IPv4 or IPv6 CIDR block.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`
}

type TrustAccessPolicyExcludeIPListInitParameters struct {

	// The ID of a previously created IP list.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TrustAccessPolicyExcludeIPListObservation struct {

	// The ID of a previously created IP list.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TrustAccessPolicyExcludeIPListParameters struct {

	// The ID of a previously created IP list.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type TrustAccessPolicyExcludeIPObservation struct {

	// An IPv4 or IPv6 CIDR block.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`
}

type TrustAccessPolicyExcludeIPParameters struct {

	// An IPv4 or IPv6 CIDR block.
	// +kubebuilder:validation:Optional
	IP *string `json:"ip" tf:"ip,omitempty"`
}

type TrustAccessPolicyExcludeInitParameters struct {
	AnyValidServiceToken *TrustAccessPolicyExcludeAnyValidServiceTokenInitParameters `json:"anyValidServiceToken,omitempty" tf:"any_valid_service_token,omitempty"`

	AuthContext *TrustAccessPolicyExcludeAuthContextInitParameters `json:"authContext,omitempty" tf:"auth_context,omitempty"`

	AuthMethod *TrustAccessPolicyExcludeAuthMethodInitParameters `json:"authMethod,omitempty" tf:"auth_method,omitempty"`

	AzureAd *TrustAccessPolicyExcludeAzureAdInitParameters `json:"azureAd,omitempty" tf:"azure_ad,omitempty"`

	Certificate *TrustAccessPolicyExcludeCertificateInitParameters `json:"certificate,omitempty" tf:"certificate,omitempty"`

	CommonName *TrustAccessPolicyExcludeCommonNameInitParameters `json:"commonName,omitempty" tf:"common_name,omitempty"`

	DevicePosture *TrustAccessPolicyExcludeDevicePostureInitParameters `json:"devicePosture,omitempty" tf:"device_posture,omitempty"`

	Email *TrustAccessPolicyExcludeEmailInitParameters `json:"email,omitempty" tf:"email,omitempty"`

	EmailDomain *TrustAccessPolicyExcludeEmailDomainInitParameters `json:"emailDomain,omitempty" tf:"email_domain,omitempty"`

	EmailList *TrustAccessPolicyExcludeEmailListInitParameters `json:"emailList,omitempty" tf:"email_list,omitempty"`

	Everyone *TrustAccessPolicyExcludeEveryoneInitParameters `json:"everyone,omitempty" tf:"everyone,omitempty"`

	ExternalEvaluation *TrustAccessPolicyExcludeExternalEvaluationInitParameters `json:"externalEvaluation,omitempty" tf:"external_evaluation,omitempty"`

	Geo *TrustAccessPolicyExcludeGeoInitParameters `json:"geo,omitempty" tf:"geo,omitempty"`

	GithubOrganization *TrustAccessPolicyExcludeGithubOrganizationInitParameters `json:"githubOrganization,omitempty" tf:"github_organization,omitempty"`

	Group *TrustAccessPolicyExcludeGroupInitParameters `json:"group,omitempty" tf:"group,omitempty"`

	Gsuite *TrustAccessPolicyExcludeGsuiteInitParameters `json:"gsuite,omitempty" tf:"gsuite,omitempty"`

	IP *TrustAccessPolicyExcludeIPInitParameters `json:"ip,omitempty" tf:"ip,omitempty"`

	IPList *TrustAccessPolicyExcludeIPListInitParameters `json:"ipList,omitempty" tf:"ip_list,omitempty"`

	LinkedAppToken *TrustAccessPolicyExcludeLinkedAppTokenInitParameters `json:"linkedAppToken,omitempty" tf:"linked_app_token,omitempty"`

	LoginMethod *TrustAccessPolicyExcludeLoginMethodInitParameters `json:"loginMethod,omitempty" tf:"login_method,omitempty"`

	Oidc *TrustAccessPolicyExcludeOidcInitParameters `json:"oidc,omitempty" tf:"oidc,omitempty"`

	Okta *TrustAccessPolicyExcludeOktaInitParameters `json:"okta,omitempty" tf:"okta,omitempty"`

	SAML *TrustAccessPolicyExcludeSAMLInitParameters `json:"saml,omitempty" tf:"saml,omitempty"`

	ServiceToken *TrustAccessPolicyExcludeServiceTokenInitParameters `json:"serviceToken,omitempty" tf:"service_token,omitempty"`
}

type TrustAccessPolicyExcludeLinkedAppTokenInitParameters struct {

	// The ID of an Access OIDC SaaS application
	AppUID *string `json:"appUid,omitempty" tf:"app_uid,omitempty"`
}

type TrustAccessPolicyExcludeLinkedAppTokenObservation struct {

	// The ID of an Access OIDC SaaS application
	AppUID *string `json:"appUid,omitempty" tf:"app_uid,omitempty"`
}

type TrustAccessPolicyExcludeLinkedAppTokenParameters struct {

	// The ID of an Access OIDC SaaS application
	// +kubebuilder:validation:Optional
	AppUID *string `json:"appUid" tf:"app_uid,omitempty"`
}

type TrustAccessPolicyExcludeLoginMethodInitParameters struct {

	// The ID of an identity provider.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TrustAccessPolicyExcludeLoginMethodObservation struct {

	// The ID of an identity provider.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TrustAccessPolicyExcludeLoginMethodParameters struct {

	// The ID of an identity provider.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type TrustAccessPolicyExcludeObservation struct {
	AnyValidServiceToken *TrustAccessPolicyExcludeAnyValidServiceTokenParameters `json:"anyValidServiceToken,omitempty" tf:"any_valid_service_token,omitempty"`

	AuthContext *TrustAccessPolicyExcludeAuthContextObservation `json:"authContext,omitempty" tf:"auth_context,omitempty"`

	AuthMethod *TrustAccessPolicyExcludeAuthMethodObservation `json:"authMethod,omitempty" tf:"auth_method,omitempty"`

	AzureAd *TrustAccessPolicyExcludeAzureAdObservation `json:"azureAd,omitempty" tf:"azure_ad,omitempty"`

	Certificate *TrustAccessPolicyExcludeCertificateParameters `json:"certificate,omitempty" tf:"certificate,omitempty"`

	CommonName *TrustAccessPolicyExcludeCommonNameObservation `json:"commonName,omitempty" tf:"common_name,omitempty"`

	DevicePosture *TrustAccessPolicyExcludeDevicePostureObservation `json:"devicePosture,omitempty" tf:"device_posture,omitempty"`

	Email *TrustAccessPolicyExcludeEmailObservation `json:"email,omitempty" tf:"email,omitempty"`

	EmailDomain *TrustAccessPolicyExcludeEmailDomainObservation `json:"emailDomain,omitempty" tf:"email_domain,omitempty"`

	EmailList *TrustAccessPolicyExcludeEmailListObservation `json:"emailList,omitempty" tf:"email_list,omitempty"`

	Everyone *TrustAccessPolicyExcludeEveryoneParameters `json:"everyone,omitempty" tf:"everyone,omitempty"`

	ExternalEvaluation *TrustAccessPolicyExcludeExternalEvaluationObservation `json:"externalEvaluation,omitempty" tf:"external_evaluation,omitempty"`

	Geo *TrustAccessPolicyExcludeGeoObservation `json:"geo,omitempty" tf:"geo,omitempty"`

	GithubOrganization *TrustAccessPolicyExcludeGithubOrganizationObservation `json:"githubOrganization,omitempty" tf:"github_organization,omitempty"`

	Group *TrustAccessPolicyExcludeGroupObservation `json:"group,omitempty" tf:"group,omitempty"`

	Gsuite *TrustAccessPolicyExcludeGsuiteObservation `json:"gsuite,omitempty" tf:"gsuite,omitempty"`

	IP *TrustAccessPolicyExcludeIPObservation `json:"ip,omitempty" tf:"ip,omitempty"`

	IPList *TrustAccessPolicyExcludeIPListObservation `json:"ipList,omitempty" tf:"ip_list,omitempty"`

	LinkedAppToken *TrustAccessPolicyExcludeLinkedAppTokenObservation `json:"linkedAppToken,omitempty" tf:"linked_app_token,omitempty"`

	LoginMethod *TrustAccessPolicyExcludeLoginMethodObservation `json:"loginMethod,omitempty" tf:"login_method,omitempty"`

	Oidc *TrustAccessPolicyExcludeOidcObservation `json:"oidc,omitempty" tf:"oidc,omitempty"`

	Okta *TrustAccessPolicyExcludeOktaObservation `json:"okta,omitempty" tf:"okta,omitempty"`

	SAML *TrustAccessPolicyExcludeSAMLObservation `json:"saml,omitempty" tf:"saml,omitempty"`

	ServiceToken *TrustAccessPolicyExcludeServiceTokenObservation `json:"serviceToken,omitempty" tf:"service_token,omitempty"`
}

type TrustAccessPolicyExcludeOidcInitParameters struct {

	// The name of the OIDC claim.
	ClaimName *string `json:"claimName,omitempty" tf:"claim_name,omitempty"`

	// The OIDC claim value to look for.
	ClaimValue *string `json:"claimValue,omitempty" tf:"claim_value,omitempty"`

	// The ID of your OIDC identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyExcludeOidcObservation struct {

	// The name of the OIDC claim.
	ClaimName *string `json:"claimName,omitempty" tf:"claim_name,omitempty"`

	// The OIDC claim value to look for.
	ClaimValue *string `json:"claimValue,omitempty" tf:"claim_value,omitempty"`

	// The ID of your OIDC identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyExcludeOidcParameters struct {

	// The name of the OIDC claim.
	// +kubebuilder:validation:Optional
	ClaimName *string `json:"claimName" tf:"claim_name,omitempty"`

	// The OIDC claim value to look for.
	// +kubebuilder:validation:Optional
	ClaimValue *string `json:"claimValue" tf:"claim_value,omitempty"`

	// The ID of your OIDC identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyExcludeOktaInitParameters struct {

	// The ID of your Okta identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// The name of the Okta group.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type TrustAccessPolicyExcludeOktaObservation struct {

	// The ID of your Okta identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// The name of the Okta group.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type TrustAccessPolicyExcludeOktaParameters struct {

	// The ID of your Okta identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId" tf:"identity_provider_id,omitempty"`

	// The name of the Okta group.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`
}

type TrustAccessPolicyExcludeParameters struct {

	// +kubebuilder:validation:Optional
	AnyValidServiceToken *TrustAccessPolicyExcludeAnyValidServiceTokenParameters `json:"anyValidServiceToken,omitempty" tf:"any_valid_service_token,omitempty"`

	// +kubebuilder:validation:Optional
	AuthContext *TrustAccessPolicyExcludeAuthContextParameters `json:"authContext,omitempty" tf:"auth_context,omitempty"`

	// +kubebuilder:validation:Optional
	AuthMethod *TrustAccessPolicyExcludeAuthMethodParameters `json:"authMethod,omitempty" tf:"auth_method,omitempty"`

	// +kubebuilder:validation:Optional
	AzureAd *TrustAccessPolicyExcludeAzureAdParameters `json:"azureAd,omitempty" tf:"azure_ad,omitempty"`

	// +kubebuilder:validation:Optional
	Certificate *TrustAccessPolicyExcludeCertificateParameters `json:"certificate,omitempty" tf:"certificate,omitempty"`

	// +kubebuilder:validation:Optional
	CommonName *TrustAccessPolicyExcludeCommonNameParameters `json:"commonName,omitempty" tf:"common_name,omitempty"`

	// +kubebuilder:validation:Optional
	DevicePosture *TrustAccessPolicyExcludeDevicePostureParameters `json:"devicePosture,omitempty" tf:"device_posture,omitempty"`

	// +kubebuilder:validation:Optional
	Email *TrustAccessPolicyExcludeEmailParameters `json:"email,omitempty" tf:"email,omitempty"`

	// +kubebuilder:validation:Optional
	EmailDomain *TrustAccessPolicyExcludeEmailDomainParameters `json:"emailDomain,omitempty" tf:"email_domain,omitempty"`

	// +kubebuilder:validation:Optional
	EmailList *TrustAccessPolicyExcludeEmailListParameters `json:"emailList,omitempty" tf:"email_list,omitempty"`

	// +kubebuilder:validation:Optional
	Everyone *TrustAccessPolicyExcludeEveryoneParameters `json:"everyone,omitempty" tf:"everyone,omitempty"`

	// +kubebuilder:validation:Optional
	ExternalEvaluation *TrustAccessPolicyExcludeExternalEvaluationParameters `json:"externalEvaluation,omitempty" tf:"external_evaluation,omitempty"`

	// +kubebuilder:validation:Optional
	Geo *TrustAccessPolicyExcludeGeoParameters `json:"geo,omitempty" tf:"geo,omitempty"`

	// +kubebuilder:validation:Optional
	GithubOrganization *TrustAccessPolicyExcludeGithubOrganizationParameters `json:"githubOrganization,omitempty" tf:"github_organization,omitempty"`

	// +kubebuilder:validation:Optional
	Group *TrustAccessPolicyExcludeGroupParameters `json:"group,omitempty" tf:"group,omitempty"`

	// +kubebuilder:validation:Optional
	Gsuite *TrustAccessPolicyExcludeGsuiteParameters `json:"gsuite,omitempty" tf:"gsuite,omitempty"`

	// +kubebuilder:validation:Optional
	IP *TrustAccessPolicyExcludeIPParameters `json:"ip,omitempty" tf:"ip,omitempty"`

	// +kubebuilder:validation:Optional
	IPList *TrustAccessPolicyExcludeIPListParameters `json:"ipList,omitempty" tf:"ip_list,omitempty"`

	// +kubebuilder:validation:Optional
	LinkedAppToken *TrustAccessPolicyExcludeLinkedAppTokenParameters `json:"linkedAppToken,omitempty" tf:"linked_app_token,omitempty"`

	// +kubebuilder:validation:Optional
	LoginMethod *TrustAccessPolicyExcludeLoginMethodParameters `json:"loginMethod,omitempty" tf:"login_method,omitempty"`

	// +kubebuilder:validation:Optional
	Oidc *TrustAccessPolicyExcludeOidcParameters `json:"oidc,omitempty" tf:"oidc,omitempty"`

	// +kubebuilder:validation:Optional
	Okta *TrustAccessPolicyExcludeOktaParameters `json:"okta,omitempty" tf:"okta,omitempty"`

	// +kubebuilder:validation:Optional
	SAML *TrustAccessPolicyExcludeSAMLParameters `json:"saml,omitempty" tf:"saml,omitempty"`

	// +kubebuilder:validation:Optional
	ServiceToken *TrustAccessPolicyExcludeServiceTokenParameters `json:"serviceToken,omitempty" tf:"service_token,omitempty"`
}

type TrustAccessPolicyExcludeSAMLInitParameters struct {

	// The name of the SAML attribute.
	AttributeName *string `json:"attributeName,omitempty" tf:"attribute_name,omitempty"`

	// The SAML attribute value to look for.
	AttributeValue *string `json:"attributeValue,omitempty" tf:"attribute_value,omitempty"`

	// The ID of your SAML identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyExcludeSAMLObservation struct {

	// The name of the SAML attribute.
	AttributeName *string `json:"attributeName,omitempty" tf:"attribute_name,omitempty"`

	// The SAML attribute value to look for.
	AttributeValue *string `json:"attributeValue,omitempty" tf:"attribute_value,omitempty"`

	// The ID of your SAML identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyExcludeSAMLParameters struct {

	// The name of the SAML attribute.
	// +kubebuilder:validation:Optional
	AttributeName *string `json:"attributeName" tf:"attribute_name,omitempty"`

	// The SAML attribute value to look for.
	// +kubebuilder:validation:Optional
	AttributeValue *string `json:"attributeValue" tf:"attribute_value,omitempty"`

	// The ID of your SAML identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyExcludeServiceTokenInitParameters struct {

	// The ID of a Service Token.
	TokenID *string `json:"tokenId,omitempty" tf:"token_id,omitempty"`
}

type TrustAccessPolicyExcludeServiceTokenObservation struct {

	// The ID of a Service Token.
	TokenID *string `json:"tokenId,omitempty" tf:"token_id,omitempty"`
}

type TrustAccessPolicyExcludeServiceTokenParameters struct {

	// The ID of a Service Token.
	// +kubebuilder:validation:Optional
	TokenID *string `json:"tokenId" tf:"token_id,omitempty"`
}

type TrustAccessPolicyIncludeAnyValidServiceTokenInitParameters struct {
}

type TrustAccessPolicyIncludeAnyValidServiceTokenObservation struct {
}

type TrustAccessPolicyIncludeAnyValidServiceTokenParameters struct {
}

type TrustAccessPolicyIncludeAuthContextInitParameters struct {

	// The ACID of an Authentication context.
	AcID *string `json:"acId,omitempty" tf:"ac_id,omitempty"`

	// The ID of an Authentication context.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of your Azure identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyIncludeAuthContextObservation struct {

	// The ACID of an Authentication context.
	AcID *string `json:"acId,omitempty" tf:"ac_id,omitempty"`

	// The ID of an Authentication context.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of your Azure identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyIncludeAuthContextParameters struct {

	// The ACID of an Authentication context.
	// +kubebuilder:validation:Optional
	AcID *string `json:"acId" tf:"ac_id,omitempty"`

	// The ID of an Authentication context.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// The ID of your Azure identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyIncludeAuthMethodInitParameters struct {

	// The type of authentication method https://datatracker.ietf.org/doc/html/rfc8176#section-2.
	AuthMethod *string `json:"authMethod,omitempty" tf:"auth_method,omitempty"`
}

type TrustAccessPolicyIncludeAuthMethodObservation struct {

	// The type of authentication method https://datatracker.ietf.org/doc/html/rfc8176#section-2.
	AuthMethod *string `json:"authMethod,omitempty" tf:"auth_method,omitempty"`
}

type TrustAccessPolicyIncludeAuthMethodParameters struct {

	// The type of authentication method https://datatracker.ietf.org/doc/html/rfc8176#section-2.
	// +kubebuilder:validation:Optional
	AuthMethod *string `json:"authMethod" tf:"auth_method,omitempty"`
}

type TrustAccessPolicyIncludeAzureAdInitParameters struct {

	// The ID of an Azure group.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of your Azure identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyIncludeAzureAdObservation struct {

	// The ID of an Azure group.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of your Azure identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyIncludeAzureAdParameters struct {

	// The ID of an Azure group.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// The ID of your Azure identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyIncludeCertificateInitParameters struct {
}

type TrustAccessPolicyIncludeCertificateObservation struct {
}

type TrustAccessPolicyIncludeCertificateParameters struct {
}

type TrustAccessPolicyIncludeCommonNameInitParameters struct {

	// The common name to match.
	CommonName *string `json:"commonName,omitempty" tf:"common_name,omitempty"`
}

type TrustAccessPolicyIncludeCommonNameObservation struct {

	// The common name to match.
	CommonName *string `json:"commonName,omitempty" tf:"common_name,omitempty"`
}

type TrustAccessPolicyIncludeCommonNameParameters struct {

	// The common name to match.
	// +kubebuilder:validation:Optional
	CommonName *string `json:"commonName" tf:"common_name,omitempty"`
}

type TrustAccessPolicyIncludeDevicePostureInitParameters struct {

	// The ID of a device posture integration.
	IntegrationUID *string `json:"integrationUid,omitempty" tf:"integration_uid,omitempty"`
}

type TrustAccessPolicyIncludeDevicePostureObservation struct {

	// The ID of a device posture integration.
	IntegrationUID *string `json:"integrationUid,omitempty" tf:"integration_uid,omitempty"`
}

type TrustAccessPolicyIncludeDevicePostureParameters struct {

	// The ID of a device posture integration.
	// +kubebuilder:validation:Optional
	IntegrationUID *string `json:"integrationUid" tf:"integration_uid,omitempty"`
}

type TrustAccessPolicyIncludeEmailDomainInitParameters struct {

	// The email domain to match.
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`
}

type TrustAccessPolicyIncludeEmailDomainObservation struct {

	// The email domain to match.
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`
}

type TrustAccessPolicyIncludeEmailDomainParameters struct {

	// The email domain to match.
	// +kubebuilder:validation:Optional
	Domain *string `json:"domain" tf:"domain,omitempty"`
}

type TrustAccessPolicyIncludeEmailInitParameters struct {

	// The email of the user.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type TrustAccessPolicyIncludeEmailListInitParameters struct {

	// The ID of a previously created email list.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TrustAccessPolicyIncludeEmailListObservation struct {

	// The ID of a previously created email list.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TrustAccessPolicyIncludeEmailListParameters struct {

	// The ID of a previously created email list.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type TrustAccessPolicyIncludeEmailObservation struct {

	// The email of the user.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type TrustAccessPolicyIncludeEmailParameters struct {

	// The email of the user.
	// +kubebuilder:validation:Optional
	Email *string `json:"email" tf:"email,omitempty"`
}

type TrustAccessPolicyIncludeEveryoneInitParameters struct {
}

type TrustAccessPolicyIncludeEveryoneObservation struct {
}

type TrustAccessPolicyIncludeEveryoneParameters struct {
}

type TrustAccessPolicyIncludeExternalEvaluationInitParameters struct {

	// The API endpoint containing your business logic.
	EvaluateURL *string `json:"evaluateUrl,omitempty" tf:"evaluate_url,omitempty"`

	// The API endpoint containing the key that Access uses to verify that the response came from your API.
	KeysURL *string `json:"keysUrl,omitempty" tf:"keys_url,omitempty"`
}

type TrustAccessPolicyIncludeExternalEvaluationObservation struct {

	// The API endpoint containing your business logic.
	EvaluateURL *string `json:"evaluateUrl,omitempty" tf:"evaluate_url,omitempty"`

	// The API endpoint containing the key that Access uses to verify that the response came from your API.
	KeysURL *string `json:"keysUrl,omitempty" tf:"keys_url,omitempty"`
}

type TrustAccessPolicyIncludeExternalEvaluationParameters struct {

	// The API endpoint containing your business logic.
	// +kubebuilder:validation:Optional
	EvaluateURL *string `json:"evaluateUrl" tf:"evaluate_url,omitempty"`

	// The API endpoint containing the key that Access uses to verify that the response came from your API.
	// +kubebuilder:validation:Optional
	KeysURL *string `json:"keysUrl" tf:"keys_url,omitempty"`
}

type TrustAccessPolicyIncludeGeoInitParameters struct {

	// The country code that should be matched.
	CountryCode *string `json:"countryCode,omitempty" tf:"country_code,omitempty"`
}

type TrustAccessPolicyIncludeGeoObservation struct {

	// The country code that should be matched.
	CountryCode *string `json:"countryCode,omitempty" tf:"country_code,omitempty"`
}

type TrustAccessPolicyIncludeGeoParameters struct {

	// The country code that should be matched.
	// +kubebuilder:validation:Optional
	CountryCode *string `json:"countryCode" tf:"country_code,omitempty"`
}

type TrustAccessPolicyIncludeGithubOrganizationInitParameters struct {

	// The ID of your Github identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// The name of the organization.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of the team
	Team *string `json:"team,omitempty" tf:"team,omitempty"`
}

type TrustAccessPolicyIncludeGithubOrganizationObservation struct {

	// The ID of your Github identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// The name of the organization.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of the team
	Team *string `json:"team,omitempty" tf:"team,omitempty"`
}

type TrustAccessPolicyIncludeGithubOrganizationParameters struct {

	// The ID of your Github identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId" tf:"identity_provider_id,omitempty"`

	// The name of the organization.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// The name of the team
	// +kubebuilder:validation:Optional
	Team *string `json:"team,omitempty" tf:"team,omitempty"`
}

type TrustAccessPolicyIncludeGroupInitParameters struct {

	// The ID of a previously created Access group.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TrustAccessPolicyIncludeGroupObservation struct {

	// The ID of a previously created Access group.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TrustAccessPolicyIncludeGroupParameters struct {

	// The ID of a previously created Access group.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type TrustAccessPolicyIncludeGsuiteInitParameters struct {

	// The email of the Google Workspace group.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// The ID of your Google Workspace identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyIncludeGsuiteObservation struct {

	// The email of the Google Workspace group.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// The ID of your Google Workspace identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyIncludeGsuiteParameters struct {

	// The email of the Google Workspace group.
	// +kubebuilder:validation:Optional
	Email *string `json:"email" tf:"email,omitempty"`

	// The ID of your Google Workspace identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyIncludeIPInitParameters struct {

	// An IPv4 or IPv6 CIDR block.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`
}

type TrustAccessPolicyIncludeIPListInitParameters struct {

	// The ID of a previously created IP list.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TrustAccessPolicyIncludeIPListObservation struct {

	// The ID of a previously created IP list.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TrustAccessPolicyIncludeIPListParameters struct {

	// The ID of a previously created IP list.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type TrustAccessPolicyIncludeIPObservation struct {

	// An IPv4 or IPv6 CIDR block.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`
}

type TrustAccessPolicyIncludeIPParameters struct {

	// An IPv4 or IPv6 CIDR block.
	// +kubebuilder:validation:Optional
	IP *string `json:"ip" tf:"ip,omitempty"`
}

type TrustAccessPolicyIncludeInitParameters struct {
	AnyValidServiceToken *TrustAccessPolicyIncludeAnyValidServiceTokenInitParameters `json:"anyValidServiceToken,omitempty" tf:"any_valid_service_token,omitempty"`

	AuthContext *TrustAccessPolicyIncludeAuthContextInitParameters `json:"authContext,omitempty" tf:"auth_context,omitempty"`

	AuthMethod *TrustAccessPolicyIncludeAuthMethodInitParameters `json:"authMethod,omitempty" tf:"auth_method,omitempty"`

	AzureAd *TrustAccessPolicyIncludeAzureAdInitParameters `json:"azureAd,omitempty" tf:"azure_ad,omitempty"`

	Certificate *TrustAccessPolicyIncludeCertificateInitParameters `json:"certificate,omitempty" tf:"certificate,omitempty"`

	CommonName *TrustAccessPolicyIncludeCommonNameInitParameters `json:"commonName,omitempty" tf:"common_name,omitempty"`

	DevicePosture *TrustAccessPolicyIncludeDevicePostureInitParameters `json:"devicePosture,omitempty" tf:"device_posture,omitempty"`

	Email *TrustAccessPolicyIncludeEmailInitParameters `json:"email,omitempty" tf:"email,omitempty"`

	EmailDomain *TrustAccessPolicyIncludeEmailDomainInitParameters `json:"emailDomain,omitempty" tf:"email_domain,omitempty"`

	EmailList *TrustAccessPolicyIncludeEmailListInitParameters `json:"emailList,omitempty" tf:"email_list,omitempty"`

	Everyone *TrustAccessPolicyIncludeEveryoneInitParameters `json:"everyone,omitempty" tf:"everyone,omitempty"`

	ExternalEvaluation *TrustAccessPolicyIncludeExternalEvaluationInitParameters `json:"externalEvaluation,omitempty" tf:"external_evaluation,omitempty"`

	Geo *TrustAccessPolicyIncludeGeoInitParameters `json:"geo,omitempty" tf:"geo,omitempty"`

	GithubOrganization *TrustAccessPolicyIncludeGithubOrganizationInitParameters `json:"githubOrganization,omitempty" tf:"github_organization,omitempty"`

	Group *TrustAccessPolicyIncludeGroupInitParameters `json:"group,omitempty" tf:"group,omitempty"`

	Gsuite *TrustAccessPolicyIncludeGsuiteInitParameters `json:"gsuite,omitempty" tf:"gsuite,omitempty"`

	IP *TrustAccessPolicyIncludeIPInitParameters `json:"ip,omitempty" tf:"ip,omitempty"`

	IPList *TrustAccessPolicyIncludeIPListInitParameters `json:"ipList,omitempty" tf:"ip_list,omitempty"`

	LinkedAppToken *TrustAccessPolicyIncludeLinkedAppTokenInitParameters `json:"linkedAppToken,omitempty" tf:"linked_app_token,omitempty"`

	LoginMethod *TrustAccessPolicyIncludeLoginMethodInitParameters `json:"loginMethod,omitempty" tf:"login_method,omitempty"`

	Oidc *TrustAccessPolicyIncludeOidcInitParameters `json:"oidc,omitempty" tf:"oidc,omitempty"`

	Okta *TrustAccessPolicyIncludeOktaInitParameters `json:"okta,omitempty" tf:"okta,omitempty"`

	SAML *TrustAccessPolicyIncludeSAMLInitParameters `json:"saml,omitempty" tf:"saml,omitempty"`

	ServiceToken *TrustAccessPolicyIncludeServiceTokenInitParameters `json:"serviceToken,omitempty" tf:"service_token,omitempty"`
}

type TrustAccessPolicyIncludeLinkedAppTokenInitParameters struct {

	// The ID of an Access OIDC SaaS application
	AppUID *string `json:"appUid,omitempty" tf:"app_uid,omitempty"`
}

type TrustAccessPolicyIncludeLinkedAppTokenObservation struct {

	// The ID of an Access OIDC SaaS application
	AppUID *string `json:"appUid,omitempty" tf:"app_uid,omitempty"`
}

type TrustAccessPolicyIncludeLinkedAppTokenParameters struct {

	// The ID of an Access OIDC SaaS application
	// +kubebuilder:validation:Optional
	AppUID *string `json:"appUid" tf:"app_uid,omitempty"`
}

type TrustAccessPolicyIncludeLoginMethodInitParameters struct {

	// The ID of an identity provider.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TrustAccessPolicyIncludeLoginMethodObservation struct {

	// The ID of an identity provider.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TrustAccessPolicyIncludeLoginMethodParameters struct {

	// The ID of an identity provider.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type TrustAccessPolicyIncludeObservation struct {
	AnyValidServiceToken *TrustAccessPolicyIncludeAnyValidServiceTokenParameters `json:"anyValidServiceToken,omitempty" tf:"any_valid_service_token,omitempty"`

	AuthContext *TrustAccessPolicyIncludeAuthContextObservation `json:"authContext,omitempty" tf:"auth_context,omitempty"`

	AuthMethod *TrustAccessPolicyIncludeAuthMethodObservation `json:"authMethod,omitempty" tf:"auth_method,omitempty"`

	AzureAd *TrustAccessPolicyIncludeAzureAdObservation `json:"azureAd,omitempty" tf:"azure_ad,omitempty"`

	Certificate *TrustAccessPolicyIncludeCertificateParameters `json:"certificate,omitempty" tf:"certificate,omitempty"`

	CommonName *TrustAccessPolicyIncludeCommonNameObservation `json:"commonName,omitempty" tf:"common_name,omitempty"`

	DevicePosture *TrustAccessPolicyIncludeDevicePostureObservation `json:"devicePosture,omitempty" tf:"device_posture,omitempty"`

	Email *TrustAccessPolicyIncludeEmailObservation `json:"email,omitempty" tf:"email,omitempty"`

	EmailDomain *TrustAccessPolicyIncludeEmailDomainObservation `json:"emailDomain,omitempty" tf:"email_domain,omitempty"`

	EmailList *TrustAccessPolicyIncludeEmailListObservation `json:"emailList,omitempty" tf:"email_list,omitempty"`

	Everyone *TrustAccessPolicyIncludeEveryoneParameters `json:"everyone,omitempty" tf:"everyone,omitempty"`

	ExternalEvaluation *TrustAccessPolicyIncludeExternalEvaluationObservation `json:"externalEvaluation,omitempty" tf:"external_evaluation,omitempty"`

	Geo *TrustAccessPolicyIncludeGeoObservation `json:"geo,omitempty" tf:"geo,omitempty"`

	GithubOrganization *TrustAccessPolicyIncludeGithubOrganizationObservation `json:"githubOrganization,omitempty" tf:"github_organization,omitempty"`

	Group *TrustAccessPolicyIncludeGroupObservation `json:"group,omitempty" tf:"group,omitempty"`

	Gsuite *TrustAccessPolicyIncludeGsuiteObservation `json:"gsuite,omitempty" tf:"gsuite,omitempty"`

	IP *TrustAccessPolicyIncludeIPObservation `json:"ip,omitempty" tf:"ip,omitempty"`

	IPList *TrustAccessPolicyIncludeIPListObservation `json:"ipList,omitempty" tf:"ip_list,omitempty"`

	LinkedAppToken *TrustAccessPolicyIncludeLinkedAppTokenObservation `json:"linkedAppToken,omitempty" tf:"linked_app_token,omitempty"`

	LoginMethod *TrustAccessPolicyIncludeLoginMethodObservation `json:"loginMethod,omitempty" tf:"login_method,omitempty"`

	Oidc *TrustAccessPolicyIncludeOidcObservation `json:"oidc,omitempty" tf:"oidc,omitempty"`

	Okta *TrustAccessPolicyIncludeOktaObservation `json:"okta,omitempty" tf:"okta,omitempty"`

	SAML *TrustAccessPolicyIncludeSAMLObservation `json:"saml,omitempty" tf:"saml,omitempty"`

	ServiceToken *TrustAccessPolicyIncludeServiceTokenObservation `json:"serviceToken,omitempty" tf:"service_token,omitempty"`
}

type TrustAccessPolicyIncludeOidcInitParameters struct {

	// The name of the OIDC claim.
	ClaimName *string `json:"claimName,omitempty" tf:"claim_name,omitempty"`

	// The OIDC claim value to look for.
	ClaimValue *string `json:"claimValue,omitempty" tf:"claim_value,omitempty"`

	// The ID of your OIDC identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyIncludeOidcObservation struct {

	// The name of the OIDC claim.
	ClaimName *string `json:"claimName,omitempty" tf:"claim_name,omitempty"`

	// The OIDC claim value to look for.
	ClaimValue *string `json:"claimValue,omitempty" tf:"claim_value,omitempty"`

	// The ID of your OIDC identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyIncludeOidcParameters struct {

	// The name of the OIDC claim.
	// +kubebuilder:validation:Optional
	ClaimName *string `json:"claimName" tf:"claim_name,omitempty"`

	// The OIDC claim value to look for.
	// +kubebuilder:validation:Optional
	ClaimValue *string `json:"claimValue" tf:"claim_value,omitempty"`

	// The ID of your OIDC identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyIncludeOktaInitParameters struct {

	// The ID of your Okta identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// The name of the Okta group.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type TrustAccessPolicyIncludeOktaObservation struct {

	// The ID of your Okta identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// The name of the Okta group.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type TrustAccessPolicyIncludeOktaParameters struct {

	// The ID of your Okta identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId" tf:"identity_provider_id,omitempty"`

	// The name of the Okta group.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`
}

type TrustAccessPolicyIncludeParameters struct {

	// +kubebuilder:validation:Optional
	AnyValidServiceToken *TrustAccessPolicyIncludeAnyValidServiceTokenParameters `json:"anyValidServiceToken,omitempty" tf:"any_valid_service_token,omitempty"`

	// +kubebuilder:validation:Optional
	AuthContext *TrustAccessPolicyIncludeAuthContextParameters `json:"authContext,omitempty" tf:"auth_context,omitempty"`

	// +kubebuilder:validation:Optional
	AuthMethod *TrustAccessPolicyIncludeAuthMethodParameters `json:"authMethod,omitempty" tf:"auth_method,omitempty"`

	// +kubebuilder:validation:Optional
	AzureAd *TrustAccessPolicyIncludeAzureAdParameters `json:"azureAd,omitempty" tf:"azure_ad,omitempty"`

	// +kubebuilder:validation:Optional
	Certificate *TrustAccessPolicyIncludeCertificateParameters `json:"certificate,omitempty" tf:"certificate,omitempty"`

	// +kubebuilder:validation:Optional
	CommonName *TrustAccessPolicyIncludeCommonNameParameters `json:"commonName,omitempty" tf:"common_name,omitempty"`

	// +kubebuilder:validation:Optional
	DevicePosture *TrustAccessPolicyIncludeDevicePostureParameters `json:"devicePosture,omitempty" tf:"device_posture,omitempty"`

	// +kubebuilder:validation:Optional
	Email *TrustAccessPolicyIncludeEmailParameters `json:"email,omitempty" tf:"email,omitempty"`

	// +kubebuilder:validation:Optional
	EmailDomain *TrustAccessPolicyIncludeEmailDomainParameters `json:"emailDomain,omitempty" tf:"email_domain,omitempty"`

	// +kubebuilder:validation:Optional
	EmailList *TrustAccessPolicyIncludeEmailListParameters `json:"emailList,omitempty" tf:"email_list,omitempty"`

	// +kubebuilder:validation:Optional
	Everyone *TrustAccessPolicyIncludeEveryoneParameters `json:"everyone,omitempty" tf:"everyone,omitempty"`

	// +kubebuilder:validation:Optional
	ExternalEvaluation *TrustAccessPolicyIncludeExternalEvaluationParameters `json:"externalEvaluation,omitempty" tf:"external_evaluation,omitempty"`

	// +kubebuilder:validation:Optional
	Geo *TrustAccessPolicyIncludeGeoParameters `json:"geo,omitempty" tf:"geo,omitempty"`

	// +kubebuilder:validation:Optional
	GithubOrganization *TrustAccessPolicyIncludeGithubOrganizationParameters `json:"githubOrganization,omitempty" tf:"github_organization,omitempty"`

	// +kubebuilder:validation:Optional
	Group *TrustAccessPolicyIncludeGroupParameters `json:"group,omitempty" tf:"group,omitempty"`

	// +kubebuilder:validation:Optional
	Gsuite *TrustAccessPolicyIncludeGsuiteParameters `json:"gsuite,omitempty" tf:"gsuite,omitempty"`

	// +kubebuilder:validation:Optional
	IP *TrustAccessPolicyIncludeIPParameters `json:"ip,omitempty" tf:"ip,omitempty"`

	// +kubebuilder:validation:Optional
	IPList *TrustAccessPolicyIncludeIPListParameters `json:"ipList,omitempty" tf:"ip_list,omitempty"`

	// +kubebuilder:validation:Optional
	LinkedAppToken *TrustAccessPolicyIncludeLinkedAppTokenParameters `json:"linkedAppToken,omitempty" tf:"linked_app_token,omitempty"`

	// +kubebuilder:validation:Optional
	LoginMethod *TrustAccessPolicyIncludeLoginMethodParameters `json:"loginMethod,omitempty" tf:"login_method,omitempty"`

	// +kubebuilder:validation:Optional
	Oidc *TrustAccessPolicyIncludeOidcParameters `json:"oidc,omitempty" tf:"oidc,omitempty"`

	// +kubebuilder:validation:Optional
	Okta *TrustAccessPolicyIncludeOktaParameters `json:"okta,omitempty" tf:"okta,omitempty"`

	// +kubebuilder:validation:Optional
	SAML *TrustAccessPolicyIncludeSAMLParameters `json:"saml,omitempty" tf:"saml,omitempty"`

	// +kubebuilder:validation:Optional
	ServiceToken *TrustAccessPolicyIncludeServiceTokenParameters `json:"serviceToken,omitempty" tf:"service_token,omitempty"`
}

type TrustAccessPolicyIncludeSAMLInitParameters struct {

	// The name of the SAML attribute.
	AttributeName *string `json:"attributeName,omitempty" tf:"attribute_name,omitempty"`

	// The SAML attribute value to look for.
	AttributeValue *string `json:"attributeValue,omitempty" tf:"attribute_value,omitempty"`

	// The ID of your SAML identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyIncludeSAMLObservation struct {

	// The name of the SAML attribute.
	AttributeName *string `json:"attributeName,omitempty" tf:"attribute_name,omitempty"`

	// The SAML attribute value to look for.
	AttributeValue *string `json:"attributeValue,omitempty" tf:"attribute_value,omitempty"`

	// The ID of your SAML identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyIncludeSAMLParameters struct {

	// The name of the SAML attribute.
	// +kubebuilder:validation:Optional
	AttributeName *string `json:"attributeName" tf:"attribute_name,omitempty"`

	// The SAML attribute value to look for.
	// +kubebuilder:validation:Optional
	AttributeValue *string `json:"attributeValue" tf:"attribute_value,omitempty"`

	// The ID of your SAML identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyIncludeServiceTokenInitParameters struct {

	// The ID of a Service Token.
	TokenID *string `json:"tokenId,omitempty" tf:"token_id,omitempty"`
}

type TrustAccessPolicyIncludeServiceTokenObservation struct {

	// The ID of a Service Token.
	TokenID *string `json:"tokenId,omitempty" tf:"token_id,omitempty"`
}

type TrustAccessPolicyIncludeServiceTokenParameters struct {

	// The ID of a Service Token.
	// +kubebuilder:validation:Optional
	TokenID *string `json:"tokenId" tf:"token_id,omitempty"`
}

type TrustAccessPolicyInitParameters struct {

	// Identifier.
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	ApprovalGroups []ApprovalGroupsInitParameters `json:"approvalGroups,omitempty" tf:"approval_groups,omitempty"`

	// Requires the user to request access from an administrator at the start of each session.
	ApprovalRequired *bool `json:"approvalRequired,omitempty" tf:"approval_required,omitempty"`

	// The action Access will take if a user matches this policy. Infrastructure application policies can only use the Allow action.
	// Available values: "allow", "deny", "non_identity", "bypass".
	Decision *string `json:"decision,omitempty" tf:"decision,omitempty"`

	Exclude []TrustAccessPolicyExcludeInitParameters `json:"exclude,omitempty" tf:"exclude,omitempty"`

	Include []TrustAccessPolicyIncludeInitParameters `json:"include,omitempty" tf:"include,omitempty"`

	// Require this application to be served in an isolated browser for users matching this policy. 'Client Web Isolation' must be on for the account in order to use this feature.
	IsolationRequired *bool `json:"isolationRequired,omitempty" tf:"isolation_required,omitempty"`

	// The name of the Access policy.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// A custom message that will appear on the purpose justification screen.
	PurposeJustificationPrompt *string `json:"purposeJustificationPrompt,omitempty" tf:"purpose_justification_prompt,omitempty"`

	// Require users to enter a justification when they log in to the application.
	PurposeJustificationRequired *bool `json:"purposeJustificationRequired,omitempty" tf:"purpose_justification_required,omitempty"`

	Require []TrustAccessPolicyRequireInitParameters `json:"require,omitempty" tf:"require,omitempty"`

	// The amount of time that tokens issued for the application will be valid. Must be in the format `300ms` or `2h45m`. Valid time units are: ns, us (or µs), ms, s, m, h.
	SessionDuration *string `json:"sessionDuration,omitempty" tf:"session_duration,omitempty"`
}

type TrustAccessPolicyObservation struct {

	// Identifier.
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	ApprovalGroups []ApprovalGroupsObservation `json:"approvalGroups,omitempty" tf:"approval_groups,omitempty"`

	// Requires the user to request access from an administrator at the start of each session.
	ApprovalRequired *bool `json:"approvalRequired,omitempty" tf:"approval_required,omitempty"`

	// The action Access will take if a user matches this policy. Infrastructure application policies can only use the Allow action.
	// Available values: "allow", "deny", "non_identity", "bypass".
	Decision *string `json:"decision,omitempty" tf:"decision,omitempty"`

	Exclude []TrustAccessPolicyExcludeObservation `json:"exclude,omitempty" tf:"exclude,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Include []TrustAccessPolicyIncludeObservation `json:"include,omitempty" tf:"include,omitempty"`

	// Require this application to be served in an isolated browser for users matching this policy. 'Client Web Isolation' must be on for the account in order to use this feature.
	IsolationRequired *bool `json:"isolationRequired,omitempty" tf:"isolation_required,omitempty"`

	// The name of the Access policy.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// A custom message that will appear on the purpose justification screen.
	PurposeJustificationPrompt *string `json:"purposeJustificationPrompt,omitempty" tf:"purpose_justification_prompt,omitempty"`

	// Require users to enter a justification when they log in to the application.
	PurposeJustificationRequired *bool `json:"purposeJustificationRequired,omitempty" tf:"purpose_justification_required,omitempty"`

	Require []TrustAccessPolicyRequireObservation `json:"require,omitempty" tf:"require,omitempty"`

	// The amount of time that tokens issued for the application will be valid. Must be in the format `300ms` or `2h45m`. Valid time units are: ns, us (or µs), ms, s, m, h.
	SessionDuration *string `json:"sessionDuration,omitempty" tf:"session_duration,omitempty"`
}

type TrustAccessPolicyParameters struct {

	// Identifier.
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// +kubebuilder:validation:Optional
	ApprovalGroups []ApprovalGroupsParameters `json:"approvalGroups,omitempty" tf:"approval_groups,omitempty"`

	// Requires the user to request access from an administrator at the start of each session.
	// +kubebuilder:validation:Optional
	ApprovalRequired *bool `json:"approvalRequired,omitempty" tf:"approval_required,omitempty"`

	// The action Access will take if a user matches this policy. Infrastructure application policies can only use the Allow action.
	// Available values: "allow", "deny", "non_identity", "bypass".
	// +kubebuilder:validation:Optional
	Decision *string `json:"decision,omitempty" tf:"decision,omitempty"`

	// +kubebuilder:validation:Optional
	Exclude []TrustAccessPolicyExcludeParameters `json:"exclude,omitempty" tf:"exclude,omitempty"`

	// +kubebuilder:validation:Optional
	Include []TrustAccessPolicyIncludeParameters `json:"include,omitempty" tf:"include,omitempty"`

	// Require this application to be served in an isolated browser for users matching this policy. 'Client Web Isolation' must be on for the account in order to use this feature.
	// +kubebuilder:validation:Optional
	IsolationRequired *bool `json:"isolationRequired,omitempty" tf:"isolation_required,omitempty"`

	// The name of the Access policy.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// A custom message that will appear on the purpose justification screen.
	// +kubebuilder:validation:Optional
	PurposeJustificationPrompt *string `json:"purposeJustificationPrompt,omitempty" tf:"purpose_justification_prompt,omitempty"`

	// Require users to enter a justification when they log in to the application.
	// +kubebuilder:validation:Optional
	PurposeJustificationRequired *bool `json:"purposeJustificationRequired,omitempty" tf:"purpose_justification_required,omitempty"`

	// +kubebuilder:validation:Optional
	Require []TrustAccessPolicyRequireParameters `json:"require,omitempty" tf:"require,omitempty"`

	// The amount of time that tokens issued for the application will be valid. Must be in the format `300ms` or `2h45m`. Valid time units are: ns, us (or µs), ms, s, m, h.
	// +kubebuilder:validation:Optional
	SessionDuration *string `json:"sessionDuration,omitempty" tf:"session_duration,omitempty"`
}

type TrustAccessPolicyRequireAnyValidServiceTokenInitParameters struct {
}

type TrustAccessPolicyRequireAnyValidServiceTokenObservation struct {
}

type TrustAccessPolicyRequireAnyValidServiceTokenParameters struct {
}

type TrustAccessPolicyRequireAuthContextInitParameters struct {

	// The ACID of an Authentication context.
	AcID *string `json:"acId,omitempty" tf:"ac_id,omitempty"`

	// The ID of an Authentication context.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of your Azure identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyRequireAuthContextObservation struct {

	// The ACID of an Authentication context.
	AcID *string `json:"acId,omitempty" tf:"ac_id,omitempty"`

	// The ID of an Authentication context.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of your Azure identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyRequireAuthContextParameters struct {

	// The ACID of an Authentication context.
	// +kubebuilder:validation:Optional
	AcID *string `json:"acId" tf:"ac_id,omitempty"`

	// The ID of an Authentication context.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// The ID of your Azure identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyRequireAuthMethodInitParameters struct {

	// The type of authentication method https://datatracker.ietf.org/doc/html/rfc8176#section-2.
	AuthMethod *string `json:"authMethod,omitempty" tf:"auth_method,omitempty"`
}

type TrustAccessPolicyRequireAuthMethodObservation struct {

	// The type of authentication method https://datatracker.ietf.org/doc/html/rfc8176#section-2.
	AuthMethod *string `json:"authMethod,omitempty" tf:"auth_method,omitempty"`
}

type TrustAccessPolicyRequireAuthMethodParameters struct {

	// The type of authentication method https://datatracker.ietf.org/doc/html/rfc8176#section-2.
	// +kubebuilder:validation:Optional
	AuthMethod *string `json:"authMethod" tf:"auth_method,omitempty"`
}

type TrustAccessPolicyRequireAzureAdInitParameters struct {

	// The ID of an Azure group.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of your Azure identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyRequireAzureAdObservation struct {

	// The ID of an Azure group.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of your Azure identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyRequireAzureAdParameters struct {

	// The ID of an Azure group.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// The ID of your Azure identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyRequireCertificateInitParameters struct {
}

type TrustAccessPolicyRequireCertificateObservation struct {
}

type TrustAccessPolicyRequireCertificateParameters struct {
}

type TrustAccessPolicyRequireCommonNameInitParameters struct {

	// The common name to match.
	CommonName *string `json:"commonName,omitempty" tf:"common_name,omitempty"`
}

type TrustAccessPolicyRequireCommonNameObservation struct {

	// The common name to match.
	CommonName *string `json:"commonName,omitempty" tf:"common_name,omitempty"`
}

type TrustAccessPolicyRequireCommonNameParameters struct {

	// The common name to match.
	// +kubebuilder:validation:Optional
	CommonName *string `json:"commonName" tf:"common_name,omitempty"`
}

type TrustAccessPolicyRequireDevicePostureInitParameters struct {

	// The ID of a device posture integration.
	IntegrationUID *string `json:"integrationUid,omitempty" tf:"integration_uid,omitempty"`
}

type TrustAccessPolicyRequireDevicePostureObservation struct {

	// The ID of a device posture integration.
	IntegrationUID *string `json:"integrationUid,omitempty" tf:"integration_uid,omitempty"`
}

type TrustAccessPolicyRequireDevicePostureParameters struct {

	// The ID of a device posture integration.
	// +kubebuilder:validation:Optional
	IntegrationUID *string `json:"integrationUid" tf:"integration_uid,omitempty"`
}

type TrustAccessPolicyRequireEmailDomainInitParameters struct {

	// The email domain to match.
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`
}

type TrustAccessPolicyRequireEmailDomainObservation struct {

	// The email domain to match.
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`
}

type TrustAccessPolicyRequireEmailDomainParameters struct {

	// The email domain to match.
	// +kubebuilder:validation:Optional
	Domain *string `json:"domain" tf:"domain,omitempty"`
}

type TrustAccessPolicyRequireEmailInitParameters struct {

	// The email of the user.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type TrustAccessPolicyRequireEmailListInitParameters struct {

	// The ID of a previously created email list.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TrustAccessPolicyRequireEmailListObservation struct {

	// The ID of a previously created email list.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TrustAccessPolicyRequireEmailListParameters struct {

	// The ID of a previously created email list.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type TrustAccessPolicyRequireEmailObservation struct {

	// The email of the user.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type TrustAccessPolicyRequireEmailParameters struct {

	// The email of the user.
	// +kubebuilder:validation:Optional
	Email *string `json:"email" tf:"email,omitempty"`
}

type TrustAccessPolicyRequireEveryoneInitParameters struct {
}

type TrustAccessPolicyRequireEveryoneObservation struct {
}

type TrustAccessPolicyRequireEveryoneParameters struct {
}

type TrustAccessPolicyRequireExternalEvaluationInitParameters struct {

	// The API endpoint containing your business logic.
	EvaluateURL *string `json:"evaluateUrl,omitempty" tf:"evaluate_url,omitempty"`

	// The API endpoint containing the key that Access uses to verify that the response came from your API.
	KeysURL *string `json:"keysUrl,omitempty" tf:"keys_url,omitempty"`
}

type TrustAccessPolicyRequireExternalEvaluationObservation struct {

	// The API endpoint containing your business logic.
	EvaluateURL *string `json:"evaluateUrl,omitempty" tf:"evaluate_url,omitempty"`

	// The API endpoint containing the key that Access uses to verify that the response came from your API.
	KeysURL *string `json:"keysUrl,omitempty" tf:"keys_url,omitempty"`
}

type TrustAccessPolicyRequireExternalEvaluationParameters struct {

	// The API endpoint containing your business logic.
	// +kubebuilder:validation:Optional
	EvaluateURL *string `json:"evaluateUrl" tf:"evaluate_url,omitempty"`

	// The API endpoint containing the key that Access uses to verify that the response came from your API.
	// +kubebuilder:validation:Optional
	KeysURL *string `json:"keysUrl" tf:"keys_url,omitempty"`
}

type TrustAccessPolicyRequireGeoInitParameters struct {

	// The country code that should be matched.
	CountryCode *string `json:"countryCode,omitempty" tf:"country_code,omitempty"`
}

type TrustAccessPolicyRequireGeoObservation struct {

	// The country code that should be matched.
	CountryCode *string `json:"countryCode,omitempty" tf:"country_code,omitempty"`
}

type TrustAccessPolicyRequireGeoParameters struct {

	// The country code that should be matched.
	// +kubebuilder:validation:Optional
	CountryCode *string `json:"countryCode" tf:"country_code,omitempty"`
}

type TrustAccessPolicyRequireGithubOrganizationInitParameters struct {

	// The ID of your Github identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// The name of the organization.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of the team
	Team *string `json:"team,omitempty" tf:"team,omitempty"`
}

type TrustAccessPolicyRequireGithubOrganizationObservation struct {

	// The ID of your Github identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// The name of the organization.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of the team
	Team *string `json:"team,omitempty" tf:"team,omitempty"`
}

type TrustAccessPolicyRequireGithubOrganizationParameters struct {

	// The ID of your Github identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId" tf:"identity_provider_id,omitempty"`

	// The name of the organization.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// The name of the team
	// +kubebuilder:validation:Optional
	Team *string `json:"team,omitempty" tf:"team,omitempty"`
}

type TrustAccessPolicyRequireGroupInitParameters struct {

	// The ID of a previously created Access group.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TrustAccessPolicyRequireGroupObservation struct {

	// The ID of a previously created Access group.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TrustAccessPolicyRequireGroupParameters struct {

	// The ID of a previously created Access group.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type TrustAccessPolicyRequireGsuiteInitParameters struct {

	// The email of the Google Workspace group.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// The ID of your Google Workspace identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyRequireGsuiteObservation struct {

	// The email of the Google Workspace group.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// The ID of your Google Workspace identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyRequireGsuiteParameters struct {

	// The email of the Google Workspace group.
	// +kubebuilder:validation:Optional
	Email *string `json:"email" tf:"email,omitempty"`

	// The ID of your Google Workspace identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyRequireIPInitParameters struct {

	// An IPv4 or IPv6 CIDR block.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`
}

type TrustAccessPolicyRequireIPListInitParameters struct {

	// The ID of a previously created IP list.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TrustAccessPolicyRequireIPListObservation struct {

	// The ID of a previously created IP list.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TrustAccessPolicyRequireIPListParameters struct {

	// The ID of a previously created IP list.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type TrustAccessPolicyRequireIPObservation struct {

	// An IPv4 or IPv6 CIDR block.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`
}

type TrustAccessPolicyRequireIPParameters struct {

	// An IPv4 or IPv6 CIDR block.
	// +kubebuilder:validation:Optional
	IP *string `json:"ip" tf:"ip,omitempty"`
}

type TrustAccessPolicyRequireInitParameters struct {
	AnyValidServiceToken *TrustAccessPolicyRequireAnyValidServiceTokenInitParameters `json:"anyValidServiceToken,omitempty" tf:"any_valid_service_token,omitempty"`

	AuthContext *TrustAccessPolicyRequireAuthContextInitParameters `json:"authContext,omitempty" tf:"auth_context,omitempty"`

	AuthMethod *TrustAccessPolicyRequireAuthMethodInitParameters `json:"authMethod,omitempty" tf:"auth_method,omitempty"`

	AzureAd *TrustAccessPolicyRequireAzureAdInitParameters `json:"azureAd,omitempty" tf:"azure_ad,omitempty"`

	Certificate *TrustAccessPolicyRequireCertificateInitParameters `json:"certificate,omitempty" tf:"certificate,omitempty"`

	CommonName *TrustAccessPolicyRequireCommonNameInitParameters `json:"commonName,omitempty" tf:"common_name,omitempty"`

	DevicePosture *TrustAccessPolicyRequireDevicePostureInitParameters `json:"devicePosture,omitempty" tf:"device_posture,omitempty"`

	Email *TrustAccessPolicyRequireEmailInitParameters `json:"email,omitempty" tf:"email,omitempty"`

	EmailDomain *TrustAccessPolicyRequireEmailDomainInitParameters `json:"emailDomain,omitempty" tf:"email_domain,omitempty"`

	EmailList *TrustAccessPolicyRequireEmailListInitParameters `json:"emailList,omitempty" tf:"email_list,omitempty"`

	Everyone *TrustAccessPolicyRequireEveryoneInitParameters `json:"everyone,omitempty" tf:"everyone,omitempty"`

	ExternalEvaluation *TrustAccessPolicyRequireExternalEvaluationInitParameters `json:"externalEvaluation,omitempty" tf:"external_evaluation,omitempty"`

	Geo *TrustAccessPolicyRequireGeoInitParameters `json:"geo,omitempty" tf:"geo,omitempty"`

	GithubOrganization *TrustAccessPolicyRequireGithubOrganizationInitParameters `json:"githubOrganization,omitempty" tf:"github_organization,omitempty"`

	Group *TrustAccessPolicyRequireGroupInitParameters `json:"group,omitempty" tf:"group,omitempty"`

	Gsuite *TrustAccessPolicyRequireGsuiteInitParameters `json:"gsuite,omitempty" tf:"gsuite,omitempty"`

	IP *TrustAccessPolicyRequireIPInitParameters `json:"ip,omitempty" tf:"ip,omitempty"`

	IPList *TrustAccessPolicyRequireIPListInitParameters `json:"ipList,omitempty" tf:"ip_list,omitempty"`

	LinkedAppToken *TrustAccessPolicyRequireLinkedAppTokenInitParameters `json:"linkedAppToken,omitempty" tf:"linked_app_token,omitempty"`

	LoginMethod *TrustAccessPolicyRequireLoginMethodInitParameters `json:"loginMethod,omitempty" tf:"login_method,omitempty"`

	Oidc *TrustAccessPolicyRequireOidcInitParameters `json:"oidc,omitempty" tf:"oidc,omitempty"`

	Okta *TrustAccessPolicyRequireOktaInitParameters `json:"okta,omitempty" tf:"okta,omitempty"`

	SAML *TrustAccessPolicyRequireSAMLInitParameters `json:"saml,omitempty" tf:"saml,omitempty"`

	ServiceToken *TrustAccessPolicyRequireServiceTokenInitParameters `json:"serviceToken,omitempty" tf:"service_token,omitempty"`
}

type TrustAccessPolicyRequireLinkedAppTokenInitParameters struct {

	// The ID of an Access OIDC SaaS application
	AppUID *string `json:"appUid,omitempty" tf:"app_uid,omitempty"`
}

type TrustAccessPolicyRequireLinkedAppTokenObservation struct {

	// The ID of an Access OIDC SaaS application
	AppUID *string `json:"appUid,omitempty" tf:"app_uid,omitempty"`
}

type TrustAccessPolicyRequireLinkedAppTokenParameters struct {

	// The ID of an Access OIDC SaaS application
	// +kubebuilder:validation:Optional
	AppUID *string `json:"appUid" tf:"app_uid,omitempty"`
}

type TrustAccessPolicyRequireLoginMethodInitParameters struct {

	// The ID of an identity provider.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TrustAccessPolicyRequireLoginMethodObservation struct {

	// The ID of an identity provider.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TrustAccessPolicyRequireLoginMethodParameters struct {

	// The ID of an identity provider.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type TrustAccessPolicyRequireObservation struct {
	AnyValidServiceToken *TrustAccessPolicyRequireAnyValidServiceTokenParameters `json:"anyValidServiceToken,omitempty" tf:"any_valid_service_token,omitempty"`

	AuthContext *TrustAccessPolicyRequireAuthContextObservation `json:"authContext,omitempty" tf:"auth_context,omitempty"`

	AuthMethod *TrustAccessPolicyRequireAuthMethodObservation `json:"authMethod,omitempty" tf:"auth_method,omitempty"`

	AzureAd *TrustAccessPolicyRequireAzureAdObservation `json:"azureAd,omitempty" tf:"azure_ad,omitempty"`

	Certificate *TrustAccessPolicyRequireCertificateParameters `json:"certificate,omitempty" tf:"certificate,omitempty"`

	CommonName *TrustAccessPolicyRequireCommonNameObservation `json:"commonName,omitempty" tf:"common_name,omitempty"`

	DevicePosture *TrustAccessPolicyRequireDevicePostureObservation `json:"devicePosture,omitempty" tf:"device_posture,omitempty"`

	Email *TrustAccessPolicyRequireEmailObservation `json:"email,omitempty" tf:"email,omitempty"`

	EmailDomain *TrustAccessPolicyRequireEmailDomainObservation `json:"emailDomain,omitempty" tf:"email_domain,omitempty"`

	EmailList *TrustAccessPolicyRequireEmailListObservation `json:"emailList,omitempty" tf:"email_list,omitempty"`

	Everyone *TrustAccessPolicyRequireEveryoneParameters `json:"everyone,omitempty" tf:"everyone,omitempty"`

	ExternalEvaluation *TrustAccessPolicyRequireExternalEvaluationObservation `json:"externalEvaluation,omitempty" tf:"external_evaluation,omitempty"`

	Geo *TrustAccessPolicyRequireGeoObservation `json:"geo,omitempty" tf:"geo,omitempty"`

	GithubOrganization *TrustAccessPolicyRequireGithubOrganizationObservation `json:"githubOrganization,omitempty" tf:"github_organization,omitempty"`

	Group *TrustAccessPolicyRequireGroupObservation `json:"group,omitempty" tf:"group,omitempty"`

	Gsuite *TrustAccessPolicyRequireGsuiteObservation `json:"gsuite,omitempty" tf:"gsuite,omitempty"`

	IP *TrustAccessPolicyRequireIPObservation `json:"ip,omitempty" tf:"ip,omitempty"`

	IPList *TrustAccessPolicyRequireIPListObservation `json:"ipList,omitempty" tf:"ip_list,omitempty"`

	LinkedAppToken *TrustAccessPolicyRequireLinkedAppTokenObservation `json:"linkedAppToken,omitempty" tf:"linked_app_token,omitempty"`

	LoginMethod *TrustAccessPolicyRequireLoginMethodObservation `json:"loginMethod,omitempty" tf:"login_method,omitempty"`

	Oidc *TrustAccessPolicyRequireOidcObservation `json:"oidc,omitempty" tf:"oidc,omitempty"`

	Okta *TrustAccessPolicyRequireOktaObservation `json:"okta,omitempty" tf:"okta,omitempty"`

	SAML *TrustAccessPolicyRequireSAMLObservation `json:"saml,omitempty" tf:"saml,omitempty"`

	ServiceToken *TrustAccessPolicyRequireServiceTokenObservation `json:"serviceToken,omitempty" tf:"service_token,omitempty"`
}

type TrustAccessPolicyRequireOidcInitParameters struct {

	// The name of the OIDC claim.
	ClaimName *string `json:"claimName,omitempty" tf:"claim_name,omitempty"`

	// The OIDC claim value to look for.
	ClaimValue *string `json:"claimValue,omitempty" tf:"claim_value,omitempty"`

	// The ID of your OIDC identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyRequireOidcObservation struct {

	// The name of the OIDC claim.
	ClaimName *string `json:"claimName,omitempty" tf:"claim_name,omitempty"`

	// The OIDC claim value to look for.
	ClaimValue *string `json:"claimValue,omitempty" tf:"claim_value,omitempty"`

	// The ID of your OIDC identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyRequireOidcParameters struct {

	// The name of the OIDC claim.
	// +kubebuilder:validation:Optional
	ClaimName *string `json:"claimName" tf:"claim_name,omitempty"`

	// The OIDC claim value to look for.
	// +kubebuilder:validation:Optional
	ClaimValue *string `json:"claimValue" tf:"claim_value,omitempty"`

	// The ID of your OIDC identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyRequireOktaInitParameters struct {

	// The ID of your Okta identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// The name of the Okta group.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type TrustAccessPolicyRequireOktaObservation struct {

	// The ID of your Okta identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`

	// The name of the Okta group.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type TrustAccessPolicyRequireOktaParameters struct {

	// The ID of your Okta identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId" tf:"identity_provider_id,omitempty"`

	// The name of the Okta group.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`
}

type TrustAccessPolicyRequireParameters struct {

	// +kubebuilder:validation:Optional
	AnyValidServiceToken *TrustAccessPolicyRequireAnyValidServiceTokenParameters `json:"anyValidServiceToken,omitempty" tf:"any_valid_service_token,omitempty"`

	// +kubebuilder:validation:Optional
	AuthContext *TrustAccessPolicyRequireAuthContextParameters `json:"authContext,omitempty" tf:"auth_context,omitempty"`

	// +kubebuilder:validation:Optional
	AuthMethod *TrustAccessPolicyRequireAuthMethodParameters `json:"authMethod,omitempty" tf:"auth_method,omitempty"`

	// +kubebuilder:validation:Optional
	AzureAd *TrustAccessPolicyRequireAzureAdParameters `json:"azureAd,omitempty" tf:"azure_ad,omitempty"`

	// +kubebuilder:validation:Optional
	Certificate *TrustAccessPolicyRequireCertificateParameters `json:"certificate,omitempty" tf:"certificate,omitempty"`

	// +kubebuilder:validation:Optional
	CommonName *TrustAccessPolicyRequireCommonNameParameters `json:"commonName,omitempty" tf:"common_name,omitempty"`

	// +kubebuilder:validation:Optional
	DevicePosture *TrustAccessPolicyRequireDevicePostureParameters `json:"devicePosture,omitempty" tf:"device_posture,omitempty"`

	// +kubebuilder:validation:Optional
	Email *TrustAccessPolicyRequireEmailParameters `json:"email,omitempty" tf:"email,omitempty"`

	// +kubebuilder:validation:Optional
	EmailDomain *TrustAccessPolicyRequireEmailDomainParameters `json:"emailDomain,omitempty" tf:"email_domain,omitempty"`

	// +kubebuilder:validation:Optional
	EmailList *TrustAccessPolicyRequireEmailListParameters `json:"emailList,omitempty" tf:"email_list,omitempty"`

	// +kubebuilder:validation:Optional
	Everyone *TrustAccessPolicyRequireEveryoneParameters `json:"everyone,omitempty" tf:"everyone,omitempty"`

	// +kubebuilder:validation:Optional
	ExternalEvaluation *TrustAccessPolicyRequireExternalEvaluationParameters `json:"externalEvaluation,omitempty" tf:"external_evaluation,omitempty"`

	// +kubebuilder:validation:Optional
	Geo *TrustAccessPolicyRequireGeoParameters `json:"geo,omitempty" tf:"geo,omitempty"`

	// +kubebuilder:validation:Optional
	GithubOrganization *TrustAccessPolicyRequireGithubOrganizationParameters `json:"githubOrganization,omitempty" tf:"github_organization,omitempty"`

	// +kubebuilder:validation:Optional
	Group *TrustAccessPolicyRequireGroupParameters `json:"group,omitempty" tf:"group,omitempty"`

	// +kubebuilder:validation:Optional
	Gsuite *TrustAccessPolicyRequireGsuiteParameters `json:"gsuite,omitempty" tf:"gsuite,omitempty"`

	// +kubebuilder:validation:Optional
	IP *TrustAccessPolicyRequireIPParameters `json:"ip,omitempty" tf:"ip,omitempty"`

	// +kubebuilder:validation:Optional
	IPList *TrustAccessPolicyRequireIPListParameters `json:"ipList,omitempty" tf:"ip_list,omitempty"`

	// +kubebuilder:validation:Optional
	LinkedAppToken *TrustAccessPolicyRequireLinkedAppTokenParameters `json:"linkedAppToken,omitempty" tf:"linked_app_token,omitempty"`

	// +kubebuilder:validation:Optional
	LoginMethod *TrustAccessPolicyRequireLoginMethodParameters `json:"loginMethod,omitempty" tf:"login_method,omitempty"`

	// +kubebuilder:validation:Optional
	Oidc *TrustAccessPolicyRequireOidcParameters `json:"oidc,omitempty" tf:"oidc,omitempty"`

	// +kubebuilder:validation:Optional
	Okta *TrustAccessPolicyRequireOktaParameters `json:"okta,omitempty" tf:"okta,omitempty"`

	// +kubebuilder:validation:Optional
	SAML *TrustAccessPolicyRequireSAMLParameters `json:"saml,omitempty" tf:"saml,omitempty"`

	// +kubebuilder:validation:Optional
	ServiceToken *TrustAccessPolicyRequireServiceTokenParameters `json:"serviceToken,omitempty" tf:"service_token,omitempty"`
}

type TrustAccessPolicyRequireSAMLInitParameters struct {

	// The name of the SAML attribute.
	AttributeName *string `json:"attributeName,omitempty" tf:"attribute_name,omitempty"`

	// The SAML attribute value to look for.
	AttributeValue *string `json:"attributeValue,omitempty" tf:"attribute_value,omitempty"`

	// The ID of your SAML identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyRequireSAMLObservation struct {

	// The name of the SAML attribute.
	AttributeName *string `json:"attributeName,omitempty" tf:"attribute_name,omitempty"`

	// The SAML attribute value to look for.
	AttributeValue *string `json:"attributeValue,omitempty" tf:"attribute_value,omitempty"`

	// The ID of your SAML identity provider.
	IdentityProviderID *string `json:"identityProviderId,omitempty" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyRequireSAMLParameters struct {

	// The name of the SAML attribute.
	// +kubebuilder:validation:Optional
	AttributeName *string `json:"attributeName" tf:"attribute_name,omitempty"`

	// The SAML attribute value to look for.
	// +kubebuilder:validation:Optional
	AttributeValue *string `json:"attributeValue" tf:"attribute_value,omitempty"`

	// The ID of your SAML identity provider.
	// +kubebuilder:validation:Optional
	IdentityProviderID *string `json:"identityProviderId" tf:"identity_provider_id,omitempty"`
}

type TrustAccessPolicyRequireServiceTokenInitParameters struct {

	// The ID of a Service Token.
	TokenID *string `json:"tokenId,omitempty" tf:"token_id,omitempty"`
}

type TrustAccessPolicyRequireServiceTokenObservation struct {

	// The ID of a Service Token.
	TokenID *string `json:"tokenId,omitempty" tf:"token_id,omitempty"`
}

type TrustAccessPolicyRequireServiceTokenParameters struct {

	// The ID of a Service Token.
	// +kubebuilder:validation:Optional
	TokenID *string `json:"tokenId" tf:"token_id,omitempty"`
}

// TrustAccessPolicySpec defines the desired state of TrustAccessPolicy
type TrustAccessPolicySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TrustAccessPolicyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TrustAccessPolicyInitParameters `json:"initProvider,omitempty"`
}

// TrustAccessPolicyStatus defines the observed state of TrustAccessPolicy.
type TrustAccessPolicyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TrustAccessPolicyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TrustAccessPolicy is the Schema for the TrustAccessPolicys API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type TrustAccessPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.accountId) || (has(self.initProvider) && has(self.initProvider.accountId))",message="spec.forProvider.accountId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.decision) || (has(self.initProvider) && has(self.initProvider.decision))",message="spec.forProvider.decision is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   TrustAccessPolicySpec   `json:"spec"`
	Status TrustAccessPolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TrustAccessPolicyList contains a list of TrustAccessPolicys
type TrustAccessPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TrustAccessPolicy `json:"items"`
}

// Repository type metadata.
var (
	TrustAccessPolicy_Kind             = "TrustAccessPolicy"
	TrustAccessPolicy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TrustAccessPolicy_Kind}.String()
	TrustAccessPolicy_KindAPIVersion   = TrustAccessPolicy_Kind + "." + CRDGroupVersion.String()
	TrustAccessPolicy_GroupVersionKind = CRDGroupVersion.WithKind(TrustAccessPolicy_Kind)
)

func init() {
	SchemeBuilder.Register(&TrustAccessPolicy{}, &TrustAccessPolicyList{})
}
