// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type TrustDlpPredefinedProfileEntriesInitParameters struct {
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TrustDlpPredefinedProfileEntriesObservation struct {
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type TrustDlpPredefinedProfileEntriesParameters struct {

	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled" tf:"enabled,omitempty"`

	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type TrustDlpPredefinedProfileInitParameters struct {
	AIContextEnabled *bool `json:"aiContextEnabled,omitempty" tf:"ai_context_enabled,omitempty"`

	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	AllowedMatchCount *float64 `json:"allowedMatchCount,omitempty" tf:"allowed_match_count,omitempty"`

	ConfidenceThreshold *string `json:"confidenceThreshold,omitempty" tf:"confidence_threshold,omitempty"`

	EnabledEntries []*string `json:"enabledEntries,omitempty" tf:"enabled_entries,omitempty"`

	Entries []TrustDlpPredefinedProfileEntriesInitParameters `json:"entries,omitempty" tf:"entries,omitempty"`

	OcrEnabled *bool `json:"ocrEnabled,omitempty" tf:"ocr_enabled,omitempty"`

	ProfileID *string `json:"profileId,omitempty" tf:"profile_id,omitempty"`
}

type TrustDlpPredefinedProfileObservation struct {
	AIContextEnabled *bool `json:"aiContextEnabled,omitempty" tf:"ai_context_enabled,omitempty"`

	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	AllowedMatchCount *float64 `json:"allowedMatchCount,omitempty" tf:"allowed_match_count,omitempty"`

	ConfidenceThreshold *string `json:"confidenceThreshold,omitempty" tf:"confidence_threshold,omitempty"`

	EnabledEntries []*string `json:"enabledEntries,omitempty" tf:"enabled_entries,omitempty"`

	Entries []TrustDlpPredefinedProfileEntriesObservation `json:"entries,omitempty" tf:"entries,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of the predefined profile.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	OcrEnabled *bool `json:"ocrEnabled,omitempty" tf:"ocr_enabled,omitempty"`

	// Whether this profile can be accessed by anyone.
	OpenAccess *bool `json:"openAccess,omitempty" tf:"open_access,omitempty"`

	ProfileID *string `json:"profileId,omitempty" tf:"profile_id,omitempty"`
}

type TrustDlpPredefinedProfileParameters struct {

	// +kubebuilder:validation:Optional
	AIContextEnabled *bool `json:"aiContextEnabled,omitempty" tf:"ai_context_enabled,omitempty"`

	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// +kubebuilder:validation:Optional
	AllowedMatchCount *float64 `json:"allowedMatchCount,omitempty" tf:"allowed_match_count,omitempty"`

	// +kubebuilder:validation:Optional
	ConfidenceThreshold *string `json:"confidenceThreshold,omitempty" tf:"confidence_threshold,omitempty"`

	// +kubebuilder:validation:Optional
	EnabledEntries []*string `json:"enabledEntries,omitempty" tf:"enabled_entries,omitempty"`

	// +kubebuilder:validation:Optional
	Entries []TrustDlpPredefinedProfileEntriesParameters `json:"entries,omitempty" tf:"entries,omitempty"`

	// +kubebuilder:validation:Optional
	OcrEnabled *bool `json:"ocrEnabled,omitempty" tf:"ocr_enabled,omitempty"`

	// +kubebuilder:validation:Optional
	ProfileID *string `json:"profileId,omitempty" tf:"profile_id,omitempty"`
}

// TrustDlpPredefinedProfileSpec defines the desired state of TrustDlpPredefinedProfile
type TrustDlpPredefinedProfileSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TrustDlpPredefinedProfileParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TrustDlpPredefinedProfileInitParameters `json:"initProvider,omitempty"`
}

// TrustDlpPredefinedProfileStatus defines the observed state of TrustDlpPredefinedProfile.
type TrustDlpPredefinedProfileStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TrustDlpPredefinedProfileObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TrustDlpPredefinedProfile is the Schema for the TrustDlpPredefinedProfiles API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type TrustDlpPredefinedProfile struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.accountId) || (has(self.initProvider) && has(self.initProvider.accountId))",message="spec.forProvider.accountId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.profileId) || (has(self.initProvider) && has(self.initProvider.profileId))",message="spec.forProvider.profileId is a required parameter"
	Spec   TrustDlpPredefinedProfileSpec   `json:"spec"`
	Status TrustDlpPredefinedProfileStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TrustDlpPredefinedProfileList contains a list of TrustDlpPredefinedProfiles
type TrustDlpPredefinedProfileList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TrustDlpPredefinedProfile `json:"items"`
}

// Repository type metadata.
var (
	TrustDlpPredefinedProfile_Kind             = "TrustDlpPredefinedProfile"
	TrustDlpPredefinedProfile_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TrustDlpPredefinedProfile_Kind}.String()
	TrustDlpPredefinedProfile_KindAPIVersion   = TrustDlpPredefinedProfile_Kind + "." + CRDGroupVersion.String()
	TrustDlpPredefinedProfile_GroupVersionKind = CRDGroupVersion.WithKind(TrustDlpPredefinedProfile_Kind)
)

func init() {
	SchemeBuilder.Register(&TrustDlpPredefinedProfile{}, &TrustDlpPredefinedProfileList{})
}
