// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ContextAwarenessInitParameters struct {

	// If true, scan the context of predefined entries to only return matches surrounded by keywords.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	Skip *SkipInitParameters `json:"skip,omitempty" tf:"skip,omitempty"`
}

type ContextAwarenessObservation struct {

	// If true, scan the context of predefined entries to only return matches surrounded by keywords.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	Skip *SkipObservation `json:"skip,omitempty" tf:"skip,omitempty"`
}

type ContextAwarenessParameters struct {

	// If true, scan the context of predefined entries to only return matches surrounded by keywords.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled" tf:"enabled,omitempty"`

	// +kubebuilder:validation:Optional
	Skip *SkipParameters `json:"skip" tf:"skip,omitempty"`
}

type EntriesInitParameters struct {
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	EntryID *string `json:"entryId,omitempty" tf:"entry_id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Pattern *EntriesPatternInitParameters `json:"pattern,omitempty" tf:"pattern,omitempty"`
}

type EntriesObservation struct {
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	EntryID *string `json:"entryId,omitempty" tf:"entry_id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Pattern *EntriesPatternObservation `json:"pattern,omitempty" tf:"pattern,omitempty"`
}

type EntriesParameters struct {

	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled" tf:"enabled,omitempty"`

	// +kubebuilder:validation:Optional
	EntryID *string `json:"entryId,omitempty" tf:"entry_id,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	Pattern *EntriesPatternParameters `json:"pattern" tf:"pattern,omitempty"`
}

type EntriesPatternInitParameters struct {
	Regex *string `json:"regex,omitempty" tf:"regex,omitempty"`

	// Available values: "luhn".
	Validation *string `json:"validation,omitempty" tf:"validation,omitempty"`
}

type EntriesPatternObservation struct {
	Regex *string `json:"regex,omitempty" tf:"regex,omitempty"`

	// Available values: "luhn".
	Validation *string `json:"validation,omitempty" tf:"validation,omitempty"`
}

type EntriesPatternParameters struct {

	// +kubebuilder:validation:Optional
	Regex *string `json:"regex" tf:"regex,omitempty"`

	// Available values: "luhn".
	// +kubebuilder:validation:Optional
	Validation *string `json:"validation,omitempty" tf:"validation,omitempty"`
}

type SharedEntriesInitParameters struct {
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	EntryID *string `json:"entryId,omitempty" tf:"entry_id,omitempty"`

	// Available values: "custom", "predefined", "integration", "exact_data", "document_fingerprint".
	EntryType *string `json:"entryType,omitempty" tf:"entry_type,omitempty"`
}

type SharedEntriesObservation struct {
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	EntryID *string `json:"entryId,omitempty" tf:"entry_id,omitempty"`

	// Available values: "custom", "predefined", "integration", "exact_data", "document_fingerprint".
	EntryType *string `json:"entryType,omitempty" tf:"entry_type,omitempty"`
}

type SharedEntriesParameters struct {

	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled" tf:"enabled,omitempty"`

	// +kubebuilder:validation:Optional
	EntryID *string `json:"entryId" tf:"entry_id,omitempty"`

	// Available values: "custom", "predefined", "integration", "exact_data", "document_fingerprint".
	// +kubebuilder:validation:Optional
	EntryType *string `json:"entryType" tf:"entry_type,omitempty"`
}

type SkipInitParameters struct {

	// If the content type is a file, skip context analysis and return all matches.
	Files *bool `json:"files,omitempty" tf:"files,omitempty"`
}

type SkipObservation struct {

	// If the content type is a file, skip context analysis and return all matches.
	Files *bool `json:"files,omitempty" tf:"files,omitempty"`
}

type SkipParameters struct {

	// If the content type is a file, skip context analysis and return all matches.
	// +kubebuilder:validation:Optional
	Files *bool `json:"files" tf:"files,omitempty"`
}

type TrustDlpCustomProfileInitParameters struct {
	AIContextEnabled *bool `json:"aiContextEnabled,omitempty" tf:"ai_context_enabled,omitempty"`

	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Related DLP policies will trigger when the match count exceeds the number set.
	AllowedMatchCount *float64 `json:"allowedMatchCount,omitempty" tf:"allowed_match_count,omitempty"`

	ConfidenceThreshold *string `json:"confidenceThreshold,omitempty" tf:"confidence_threshold,omitempty"`

	ContextAwareness *ContextAwarenessInitParameters `json:"contextAwareness,omitempty" tf:"context_awareness,omitempty"`

	// The description of the profile.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	Entries []EntriesInitParameters `json:"entries,omitempty" tf:"entries,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	OcrEnabled *bool `json:"ocrEnabled,omitempty" tf:"ocr_enabled,omitempty"`

	SharedEntries []SharedEntriesInitParameters `json:"sharedEntries,omitempty" tf:"shared_entries,omitempty"`
}

type TrustDlpCustomProfileObservation struct {
	AIContextEnabled *bool `json:"aiContextEnabled,omitempty" tf:"ai_context_enabled,omitempty"`

	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Related DLP policies will trigger when the match count exceeds the number set.
	AllowedMatchCount *float64 `json:"allowedMatchCount,omitempty" tf:"allowed_match_count,omitempty"`

	ConfidenceThreshold *string `json:"confidenceThreshold,omitempty" tf:"confidence_threshold,omitempty"`

	ContextAwareness *ContextAwarenessObservation `json:"contextAwareness,omitempty" tf:"context_awareness,omitempty"`

	// When the profile was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// The description of the profile.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	Entries []EntriesObservation `json:"entries,omitempty" tf:"entries,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	OcrEnabled *bool `json:"ocrEnabled,omitempty" tf:"ocr_enabled,omitempty"`

	// Whether this profile can be accessed by anyone.
	OpenAccess *bool `json:"openAccess,omitempty" tf:"open_access,omitempty"`

	SharedEntries []SharedEntriesObservation `json:"sharedEntries,omitempty" tf:"shared_entries,omitempty"`

	// Available values: "custom", "predefined", "integration".
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// When the profile was lasted updated.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type TrustDlpCustomProfileParameters struct {

	// +kubebuilder:validation:Optional
	AIContextEnabled *bool `json:"aiContextEnabled,omitempty" tf:"ai_context_enabled,omitempty"`

	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Related DLP policies will trigger when the match count exceeds the number set.
	// +kubebuilder:validation:Optional
	AllowedMatchCount *float64 `json:"allowedMatchCount,omitempty" tf:"allowed_match_count,omitempty"`

	// +kubebuilder:validation:Optional
	ConfidenceThreshold *string `json:"confidenceThreshold,omitempty" tf:"confidence_threshold,omitempty"`

	// +kubebuilder:validation:Optional
	ContextAwareness *ContextAwarenessParameters `json:"contextAwareness,omitempty" tf:"context_awareness,omitempty"`

	// The description of the profile.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// +kubebuilder:validation:Optional
	Entries []EntriesParameters `json:"entries,omitempty" tf:"entries,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	OcrEnabled *bool `json:"ocrEnabled,omitempty" tf:"ocr_enabled,omitempty"`

	// +kubebuilder:validation:Optional
	SharedEntries []SharedEntriesParameters `json:"sharedEntries,omitempty" tf:"shared_entries,omitempty"`
}

// TrustDlpCustomProfileSpec defines the desired state of TrustDlpCustomProfile
type TrustDlpCustomProfileSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TrustDlpCustomProfileParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TrustDlpCustomProfileInitParameters `json:"initProvider,omitempty"`
}

// TrustDlpCustomProfileStatus defines the observed state of TrustDlpCustomProfile.
type TrustDlpCustomProfileStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TrustDlpCustomProfileObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TrustDlpCustomProfile is the Schema for the TrustDlpCustomProfiles API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type TrustDlpCustomProfile struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.accountId) || (has(self.initProvider) && has(self.initProvider.accountId))",message="spec.forProvider.accountId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   TrustDlpCustomProfileSpec   `json:"spec"`
	Status TrustDlpCustomProfileStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TrustDlpCustomProfileList contains a list of TrustDlpCustomProfiles
type TrustDlpCustomProfileList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TrustDlpCustomProfile `json:"items"`
}

// Repository type metadata.
var (
	TrustDlpCustomProfile_Kind             = "TrustDlpCustomProfile"
	TrustDlpCustomProfile_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TrustDlpCustomProfile_Kind}.String()
	TrustDlpCustomProfile_KindAPIVersion   = TrustDlpCustomProfile_Kind + "." + CRDGroupVersion.String()
	TrustDlpCustomProfile_GroupVersionKind = CRDGroupVersion.WithKind(TrustDlpCustomProfile_Kind)
)

func init() {
	SchemeBuilder.Register(&TrustDlpCustomProfile{}, &TrustDlpCustomProfileList{})
}
