// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type DohInitParameters struct {

	// Indicate whether the DOH endpoint is enabled for this location.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	Networks []NetworksInitParameters `json:"networks,omitempty" tf:"networks,omitempty"`

	// Specify whether the DOH endpoint requires user identity authentication.
	RequireToken *bool `json:"requireToken,omitempty" tf:"require_token,omitempty"`
}

type DohObservation struct {

	// Indicate whether the DOH endpoint is enabled for this location.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	Networks []NetworksObservation `json:"networks,omitempty" tf:"networks,omitempty"`

	// Specify whether the DOH endpoint requires user identity authentication.
	RequireToken *bool `json:"requireToken,omitempty" tf:"require_token,omitempty"`
}

type DohParameters struct {

	// Indicate whether the DOH endpoint is enabled for this location.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// +kubebuilder:validation:Optional
	Networks []NetworksParameters `json:"networks,omitempty" tf:"networks,omitempty"`

	// Specify whether the DOH endpoint requires user identity authentication.
	// +kubebuilder:validation:Optional
	RequireToken *bool `json:"requireToken,omitempty" tf:"require_token,omitempty"`
}

type DotInitParameters struct {

	// Indicate whether the DOT endpoint is enabled for this location.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	Networks []DotNetworksInitParameters `json:"networks,omitempty" tf:"networks,omitempty"`
}

type DotNetworksInitParameters struct {

	// Specify the IP address or IP CIDR.
	Network *string `json:"network,omitempty" tf:"network,omitempty"`
}

type DotNetworksObservation struct {

	// Specify the IP address or IP CIDR.
	Network *string `json:"network,omitempty" tf:"network,omitempty"`
}

type DotNetworksParameters struct {

	// Specify the IP address or IP CIDR.
	// +kubebuilder:validation:Optional
	Network *string `json:"network" tf:"network,omitempty"`
}

type DotObservation struct {

	// Indicate whether the DOT endpoint is enabled for this location.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	Networks []DotNetworksObservation `json:"networks,omitempty" tf:"networks,omitempty"`
}

type DotParameters struct {

	// Indicate whether the DOT endpoint is enabled for this location.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// +kubebuilder:validation:Optional
	Networks []DotNetworksParameters `json:"networks,omitempty" tf:"networks,omitempty"`
}

type EndpointsIPv4InitParameters struct {

	// Indicate whether the IPv4 endpoint is enabled for this location.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type EndpointsIPv4Observation struct {

	// Indicate whether the IPv4 endpoint is enabled for this location.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type EndpointsIPv4Parameters struct {

	// Indicate whether the IPv4 endpoint is enabled for this location.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type EndpointsIPv6InitParameters struct {

	// Indicate whether the IPV6 endpoint is enabled for this location.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	Networks []IPv6NetworksInitParameters `json:"networks,omitempty" tf:"networks,omitempty"`
}

type EndpointsIPv6Observation struct {

	// Indicate whether the IPV6 endpoint is enabled for this location.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	Networks []IPv6NetworksObservation `json:"networks,omitempty" tf:"networks,omitempty"`
}

type EndpointsIPv6Parameters struct {

	// Indicate whether the IPV6 endpoint is enabled for this location.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// +kubebuilder:validation:Optional
	Networks []IPv6NetworksParameters `json:"networks,omitempty" tf:"networks,omitempty"`
}

type EndpointsInitParameters struct {
	Doh *DohInitParameters `json:"doh,omitempty" tf:"doh,omitempty"`

	Dot *DotInitParameters `json:"dot,omitempty" tf:"dot,omitempty"`

	IPv4 *EndpointsIPv4InitParameters `json:"ipv4,omitempty" tf:"ipv4,omitempty"`

	IPv6 *EndpointsIPv6InitParameters `json:"ipv6,omitempty" tf:"ipv6,omitempty"`
}

type EndpointsObservation struct {
	Doh *DohObservation `json:"doh,omitempty" tf:"doh,omitempty"`

	Dot *DotObservation `json:"dot,omitempty" tf:"dot,omitempty"`

	IPv4 *EndpointsIPv4Observation `json:"ipv4,omitempty" tf:"ipv4,omitempty"`

	IPv6 *EndpointsIPv6Observation `json:"ipv6,omitempty" tf:"ipv6,omitempty"`
}

type EndpointsParameters struct {

	// +kubebuilder:validation:Optional
	Doh *DohParameters `json:"doh" tf:"doh,omitempty"`

	// +kubebuilder:validation:Optional
	Dot *DotParameters `json:"dot" tf:"dot,omitempty"`

	// +kubebuilder:validation:Optional
	IPv4 *EndpointsIPv4Parameters `json:"ipv4" tf:"ipv4,omitempty"`

	// +kubebuilder:validation:Optional
	IPv6 *EndpointsIPv6Parameters `json:"ipv6" tf:"ipv6,omitempty"`
}

type IPv6NetworksInitParameters struct {

	// Specify the IPv6 address or IPv6 CIDR.
	Network *string `json:"network,omitempty" tf:"network,omitempty"`
}

type IPv6NetworksObservation struct {

	// Specify the IPv6 address or IPv6 CIDR.
	Network *string `json:"network,omitempty" tf:"network,omitempty"`
}

type IPv6NetworksParameters struct {

	// Specify the IPv6 address or IPv6 CIDR.
	// +kubebuilder:validation:Optional
	Network *string `json:"network" tf:"network,omitempty"`
}

type NetworksInitParameters struct {

	// Specify the IP address or IP CIDR.
	Network *string `json:"network,omitempty" tf:"network,omitempty"`
}

type NetworksObservation struct {

	// Specify the IP address or IP CIDR.
	Network *string `json:"network,omitempty" tf:"network,omitempty"`
}

type NetworksParameters struct {

	// Specify the IP address or IP CIDR.
	// +kubebuilder:validation:Optional
	Network *string `json:"network" tf:"network,omitempty"`
}

type TrustDNSLocationInitParameters struct {
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Indicate whether this location is the default location.
	ClientDefault *bool `json:"clientDefault,omitempty" tf:"client_default,omitempty"`

	// Specify the identifier of the pair of IPv4 addresses assigned to this location. When creating a location, if this field is absent or set to null, the pair of shared IPv4 addresses (0e4a32c6-6fb8-4858-9296-98f51631e8e6) is auto-assigned. When updating a location, if this field is absent or set to null, the pre-assigned pair remains unchanged.
	DNSDestinationIpsID *string `json:"dnsDestinationIpsId,omitempty" tf:"dns_destination_ips_id,omitempty"`

	// Indicate whether the location must resolve EDNS queries.
	EcsSupport *bool `json:"ecsSupport,omitempty" tf:"ecs_support,omitempty"`

	Endpoints *EndpointsInitParameters `json:"endpoints,omitempty" tf:"endpoints,omitempty"`

	// Specify the location name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Networks []TrustDNSLocationNetworksInitParameters `json:"networks,omitempty" tf:"networks,omitempty"`
}

type TrustDNSLocationNetworksInitParameters struct {

	// Specify the IPv4 address or IPv4 CIDR. Limit IPv4 CIDRs to a maximum of /24.
	Network *string `json:"network,omitempty" tf:"network,omitempty"`
}

type TrustDNSLocationNetworksObservation struct {

	// Specify the IPv4 address or IPv4 CIDR. Limit IPv4 CIDRs to a maximum of /24.
	Network *string `json:"network,omitempty" tf:"network,omitempty"`
}

type TrustDNSLocationNetworksParameters struct {

	// Specify the IPv4 address or IPv4 CIDR. Limit IPv4 CIDRs to a maximum of /24.
	// +kubebuilder:validation:Optional
	Network *string `json:"network" tf:"network,omitempty"`
}

type TrustDNSLocationObservation struct {
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Indicate whether this location is the default location.
	ClientDefault *bool `json:"clientDefault,omitempty" tf:"client_default,omitempty"`

	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Specify the UUID of the IPv6 block brought to the gateway so that this location's IPv6 address is allocated from the Bring Your Own IPv6 (BYOIPv6) block rather than the standard Cloudflare IPv6 block.
	DNSDestinationIPv6BlockID *string `json:"dnsDestinationIpv6BlockId,omitempty" tf:"dns_destination_ipv6_block_id,omitempty"`

	// Specify the identifier of the pair of IPv4 addresses assigned to this location. When creating a location, if this field is absent or set to null, the pair of shared IPv4 addresses (0e4a32c6-6fb8-4858-9296-98f51631e8e6) is auto-assigned. When updating a location, if this field is absent or set to null, the pre-assigned pair remains unchanged.
	DNSDestinationIpsID *string `json:"dnsDestinationIpsId,omitempty" tf:"dns_destination_ips_id,omitempty"`

	// Specify the DNS over HTTPS domain that receives DNS requests. Gateway automatically generates this value.
	DohSubdomain *string `json:"dohSubdomain,omitempty" tf:"doh_subdomain,omitempty"`

	// Indicate whether the location must resolve EDNS queries.
	EcsSupport *bool `json:"ecsSupport,omitempty" tf:"ecs_support,omitempty"`

	Endpoints *EndpointsObservation `json:"endpoints,omitempty" tf:"endpoints,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Defines the automatically generated IPv6 destination IP assigned to this location. Gateway counts all DNS requests sent to this IP as requests under this location.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// Show the primary destination IPv4 address from the pair identified dns_destination_ips_id. This field read-only.
	IPv4Destination *string `json:"ipv4Destination,omitempty" tf:"ipv4_destination,omitempty"`

	// Show the backup destination IPv4 address from the pair identified dns_destination_ips_id. This field read-only.
	IPv4DestinationBackup *string `json:"ipv4DestinationBackup,omitempty" tf:"ipv4_destination_backup,omitempty"`

	// Specify the location name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Networks []TrustDNSLocationNetworksObservation `json:"networks,omitempty" tf:"networks,omitempty"`

	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type TrustDNSLocationParameters struct {

	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Indicate whether this location is the default location.
	// +kubebuilder:validation:Optional
	ClientDefault *bool `json:"clientDefault,omitempty" tf:"client_default,omitempty"`

	// Specify the identifier of the pair of IPv4 addresses assigned to this location. When creating a location, if this field is absent or set to null, the pair of shared IPv4 addresses (0e4a32c6-6fb8-4858-9296-98f51631e8e6) is auto-assigned. When updating a location, if this field is absent or set to null, the pre-assigned pair remains unchanged.
	// +kubebuilder:validation:Optional
	DNSDestinationIpsID *string `json:"dnsDestinationIpsId,omitempty" tf:"dns_destination_ips_id,omitempty"`

	// Indicate whether the location must resolve EDNS queries.
	// +kubebuilder:validation:Optional
	EcsSupport *bool `json:"ecsSupport,omitempty" tf:"ecs_support,omitempty"`

	// +kubebuilder:validation:Optional
	Endpoints *EndpointsParameters `json:"endpoints,omitempty" tf:"endpoints,omitempty"`

	// Specify the location name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	Networks []TrustDNSLocationNetworksParameters `json:"networks,omitempty" tf:"networks,omitempty"`
}

// TrustDNSLocationSpec defines the desired state of TrustDNSLocation
type TrustDNSLocationSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TrustDNSLocationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TrustDNSLocationInitParameters `json:"initProvider,omitempty"`
}

// TrustDNSLocationStatus defines the observed state of TrustDNSLocation.
type TrustDNSLocationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TrustDNSLocationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TrustDNSLocation is the Schema for the TrustDNSLocations API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type TrustDNSLocation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.accountId) || (has(self.initProvider) && has(self.initProvider.accountId))",message="spec.forProvider.accountId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   TrustDNSLocationSpec   `json:"spec"`
	Status TrustDNSLocationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TrustDNSLocationList contains a list of TrustDNSLocations
type TrustDNSLocationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TrustDNSLocation `json:"items"`
}

// Repository type metadata.
var (
	TrustDNSLocation_Kind             = "TrustDNSLocation"
	TrustDNSLocation_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TrustDNSLocation_Kind}.String()
	TrustDNSLocation_KindAPIVersion   = TrustDNSLocation_Kind + "." + CRDGroupVersion.String()
	TrustDNSLocation_GroupVersionKind = CRDGroupVersion.WithKind(TrustDNSLocation_Kind)
)

func init() {
	SchemeBuilder.Register(&TrustDNSLocation{}, &TrustDNSLocationList{})
}
