apiVersion: account.cloudflare.crossplane.io/v1alpha1
kind: Member
metadata:
  annotations:
    meta.upbound.io/example-id: account/v1alpha1/member
  labels:
    testing.upbound.io/example-name: example_account_member
  name: example-account-member
spec:
  forProvider:
    accountId: 023e105f4ecef8ad9ca31a8372d0c353
    email: user@example.com
    roles:
    - 3536bcfad5faccb999b47003c79917fb
    status: accepted
