apiVersion: worker.cloudflare.crossplane.io/v1alpha1
kind: Version
metadata:
  annotations:
    meta.upbound.io/example-id: worker/v1alpha1/version
  labels:
    testing.upbound.io/example-name: example_worker_version
  name: example-worker-version
spec:
  forProvider:
    accountId: 023e105f4ecef8ad9ca31a8372d0c353
    annotations:
      workersMessage: Fixed bug.
      workersTag: v1.0.1
    assets:
      config:
        htmlHandling: auto-trailing-slash
        notFoundHandling: 404-page
        runWorkerFirst:
        - string
      jwtSecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
    bindings:
    - name: MY_ENV_VAR
      textSecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
      type: plain_text
    compatibilityDate: "2021-01-01"
    compatibilityFlags:
    - nodejs_compat
    limits:
      cpuMs: 50
    mainModule: index.js
    migrations:
      deletedClasses:
      - string
      newClasses:
      - string
      newSqliteClasses:
      - string
      newTag: v2
      oldTag: v1
      renamedClasses:
      - from: from
        to: to
      transferredClasses:
      - from: from
        fromScript: from_script
        to: to
    modules:
    - contentFile: dist/index.js
      contentType: application/javascript+module
      name: index.js
    placement:
      mode: smart
    workerId: worker_id
