apiVersion: user.cloudflare.crossplane.io/v1alpha1
kind: AgentBlockingRule
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/agentblockingrule
  labels:
    testing.upbound.io/example-name: example_user_agent_blocking_rule
  name: example-user-agent-blocking-rule
spec:
  forProvider:
    configuration:
      target: ua
      value: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)
    description: Prevent multiple login failures to mitigate brute force attacks
    mode: challenge
    paused: false
    zoneId: 023e105f4ecef8ad9ca31a8372d0c353
